-- GENERATED from migrations/ — edit migrations and run npm run schema:write
-- Do not edit this file by hand; it is a canonicalized dump of the applied migrations.

CREATE TABLE IF NOT EXISTS account_token_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  account_token_id TEXT NOT NULL,
  customer_id TEXT NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('issue', 'rotate', 'revoke', 'revoke-customer', 'repepper', 'merge')),
  actor TEXT NOT NULL DEFAULT '',
  actor_type TEXT NOT NULL DEFAULT 'unknown' CHECK (actor_type IN ('access', 'dev', 'cli', 'sync', 'system', 'unknown')),
  source TEXT NOT NULL DEFAULT 'admin',
  reason TEXT NOT NULL DEFAULT '',
  request_id TEXT NOT NULL DEFAULT '',
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS account_token_revocations (
  customer_id TEXT PRIMARY KEY,
  revocation_seq INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS account_tokens (
  id TEXT PRIMARY KEY,
  customer_id TEXT NOT NULL,
  token_hmac TEXT NOT NULL,
  pepper_key_id TEXT NOT NULL,
  token_prefix TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  scopes_json TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked', 'disabled')),
  expires_at INTEGER NOT NULL,
  last_used_at INTEGER NULL,
  replaced_by TEXT NULL,
  created_by TEXT NOT NULL DEFAULT '',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
  FOREIGN KEY (replaced_by) REFERENCES account_tokens(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS audit_digests (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  source      TEXT    NOT NULL,
  up_to_id    INTEGER NOT NULL,
  event_count INTEGER NOT NULL,
  prev_digest TEXT    NOT NULL DEFAULT '',
  digest      TEXT    NOT NULL,
  created_at  INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS catalog_events (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('feature', 'plan', 'plan_feature')),
  entity_id   TEXT NOT NULL,
  project     TEXT NOT NULL,
  event_type  TEXT NOT NULL CHECK (event_type IN ('create', 'update', 'disable', 'reenable')),
  actor       TEXT NOT NULL DEFAULT '',
  actor_type  TEXT NOT NULL DEFAULT 'unknown' CHECK (actor_type IN ('access', 'dev', 'cli', 'sync', 'system', 'unknown')),
  source      TEXT NOT NULL DEFAULT 'admin',
  reason      TEXT NOT NULL DEFAULT '',
  request_id  TEXT NOT NULL DEFAULT '',
  prev_json   TEXT NOT NULL DEFAULT '',
  next_json   TEXT NOT NULL DEFAULT '',
  created_at  INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS catalog_features (
  id TEXT PRIMARY KEY,
  project TEXT NOT NULL,
  feature_key TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  category TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  UNIQUE (project, feature_key)
);

CREATE TABLE IF NOT EXISTS catalog_import_previews (
  id                       TEXT PRIMARY KEY,
  actor_subject            TEXT NOT NULL,
  source_generation        INTEGER NOT NULL,
  normalized_manifest_json TEXT NOT NULL,
  manifest_digest          TEXT NOT NULL,
  preview_json             TEXT NOT NULL,
  actions_json             TEXT NOT NULL,
  effective_at             INTEGER NOT NULL,
  expires_at               INTEGER NOT NULL,
  claim_token              TEXT NULL,
  claimed_at               INTEGER NULL,
  consumed_at              INTEGER NULL,
  applied_response_json    TEXT NULL,
  created_at               INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS catalog_plan_features (
  project TEXT NOT NULL,
  plan_id TEXT NOT NULL,
  feature_key TEXT NOT NULL,
  feature_inclusion TEXT NOT NULL DEFAULT 'included' CHECK (feature_inclusion IN ('included', 'addon')),
  addon_key TEXT NULL,
  policy_id TEXT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  display_order INTEGER NOT NULL DEFAULT 0,
  assertion_ttl_seconds INTEGER NULL,
  pool_size INTEGER NULL,
  max_active_devices INTEGER NULL,
  max_borrow_sec INTEGER NULL,
  meter_quota INTEGER NULL,
  meter_period_sec INTEGER NULL,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  PRIMARY KEY (plan_id, feature_key),
  FOREIGN KEY (project, plan_id) REFERENCES catalog_plans(project, id) ON DELETE CASCADE,
  FOREIGN KEY (project, feature_key) REFERENCES catalog_features(project, feature_key) ON DELETE CASCADE,
  FOREIGN KEY (policy_id) REFERENCES entitlement_policies(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS catalog_plans (
  id TEXT PRIMARY KEY,
  project TEXT NOT NULL,
  plan_key TEXT NOT NULL,
  name TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  version INTEGER NOT NULL DEFAULT 1,
  description TEXT NOT NULL DEFAULT '',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  UNIQUE (project, plan_key),
  UNIQUE (project, id)
);

CREATE TABLE IF NOT EXISTS customer_events (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  customer_id TEXT NOT NULL,
  event_type  TEXT NOT NULL CHECK (event_type IN ('disable', 'reenable')),
  prev_status TEXT NOT NULL,
  next_status TEXT NOT NULL,
  actor       TEXT NOT NULL DEFAULT '',
  actor_type  TEXT NOT NULL DEFAULT 'unknown' CHECK (actor_type IN ('access', 'dev', 'cli', 'sync', 'system', 'unknown')),
  source      TEXT NOT NULL DEFAULT 'admin',
  reason      TEXT NOT NULL DEFAULT '',
  request_id  TEXT NOT NULL DEFAULT '',
  created_at  INTEGER NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "customers" (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL DEFAULT '',
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  external_ref TEXT NOT NULL DEFAULT ''
, authority_revision INTEGER NOT NULL DEFAULT 0
  CHECK (authority_revision = CAST(authority_revision AS BIGINT) AND authority_revision BETWEEN 0 AND 9007199254740991));

CREATE TABLE IF NOT EXISTS device_bound_authorizations (
  handle_hash TEXT NOT NULL PRIMARY KEY,
  client_id TEXT NOT NULL,
  project TEXT NOT NULL,
  key_id TEXT NOT NULL,
  public_key_spki TEXT NOT NULL,
  device_label TEXT NOT NULL DEFAULT '',
  redirect_uri TEXT NOT NULL,
  client_state TEXT NOT NULL,
  pkce_challenge TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'consumed', 'denied')),
  revision INTEGER NOT NULL DEFAULT 0 CHECK (revision = CAST(revision AS BIGINT) AND revision BETWEEN 0 AND 9007199254740991),
  customer_id TEXT REFERENCES customers(id),
  feature TEXT,
  license_fingerprint TEXT,
  code_hash TEXT,
  code_expires_at INTEGER CHECK (code_expires_at = CAST(code_expires_at AS BIGINT) AND code_expires_at BETWEEN 0 AND 9007199254740991),
  approval_ciphertext TEXT,
  created_at INTEGER NOT NULL CHECK (created_at = CAST(created_at AS BIGINT) AND created_at BETWEEN 0 AND 9007199254740991),
  expires_at INTEGER NOT NULL CHECK (expires_at = CAST(expires_at AS BIGINT) AND expires_at > created_at AND expires_at <= 9007199254740991),
  consumed_invocation_id TEXT,
  consumed_operation_id TEXT,
  recovery_until INTEGER CHECK (recovery_until = CAST(recovery_until AS BIGINT) AND recovery_until BETWEEN 0 AND 9007199254740991), requested_feature TEXT
  CHECK(requested_feature IS NULL OR (length(requested_feature) BETWEEN 1 AND 15
    AND requested_feature NOT GLOB '*[^A-Za-z0-9_.:-]*')),
  CHECK (
    (status IN ('pending','denied') AND customer_id IS NULL AND feature IS NULL
      AND license_fingerprint IS NULL AND code_hash IS NULL AND code_expires_at IS NULL
      AND approval_ciphertext IS NULL)
    OR (status IN ('approved','consumed') AND customer_id IS NOT NULL AND feature IS NOT NULL
      AND license_fingerprint IS NOT NULL AND code_hash IS NOT NULL AND code_expires_at IS NOT NULL
      AND code_expires_at >= created_at AND code_expires_at <= expires_at)
  ),
  CHECK (
    (status != 'consumed' AND consumed_invocation_id IS NULL AND consumed_operation_id IS NULL AND recovery_until IS NULL)
    OR (status = 'consumed' AND consumed_invocation_id IS NOT NULL AND consumed_operation_id IS NOT NULL
      AND recovery_until IS NOT NULL AND recovery_until > created_at AND approval_ciphertext IS NULL)
  )
);

CREATE TABLE IF NOT EXISTS device_bound_bindings (
  id TEXT NOT NULL PRIMARY KEY,
  project TEXT NOT NULL,
  feature TEXT NOT NULL,
  license_fingerprint TEXT NOT NULL,
  device_id TEXT NOT NULL REFERENCES device_bound_devices(id),
  state TEXT NOT NULL DEFAULT 'active' CHECK (state IN ('active', 'retiring', 'released')),
  generation INTEGER NOT NULL DEFAULT 1 CHECK (generation = CAST(generation AS BIGINT) AND generation BETWEEN 1 AND 9007199254740991),
  revision INTEGER NOT NULL DEFAULT 0 CHECK (revision = CAST(revision AS BIGINT) AND revision BETWEEN 0 AND 9007199254740991),
  hold_until INTEGER NOT NULL DEFAULT 0 CHECK (hold_until = CAST(hold_until AS BIGINT) AND hold_until BETWEEN 0 AND 9007199254740991),
  created_at INTEGER NOT NULL CHECK (created_at = CAST(created_at AS BIGINT) AND created_at BETWEEN 0 AND 9007199254740991),
  updated_at INTEGER NOT NULL CHECK (updated_at = CAST(updated_at AS BIGINT) AND updated_at BETWEEN 0 AND 9007199254740991),
  FOREIGN KEY (project, feature, license_fingerprint) REFERENCES entitlements(project, feature, license_fingerprint)
);

CREATE TABLE IF NOT EXISTS device_bound_challenges (
  id TEXT NOT NULL PRIMARY KEY,
  purpose TEXT NOT NULL CHECK (purpose IN ('exchange', 'renew')),
  subject_id TEXT NOT NULL,
  key_id TEXT NOT NULL,
  operation_id TEXT NOT NULL,
  nonce_hash TEXT NOT NULL UNIQUE,
  created_at INTEGER NOT NULL CHECK (created_at = CAST(created_at AS BIGINT) AND created_at BETWEEN 0 AND 9007199254740991),
  expires_at INTEGER NOT NULL CHECK (expires_at = CAST(expires_at AS BIGINT) AND expires_at > created_at AND expires_at <= 9007199254740991),
  consumed_invocation_id TEXT
);

CREATE TABLE IF NOT EXISTS device_bound_commit_checks (
  invocation_id TEXT NOT NULL PRIMARY KEY,
  ok INTEGER NOT NULL CHECK (ok = 1)
);

CREATE TABLE IF NOT EXISTS device_bound_devices (
  id TEXT NOT NULL PRIMARY KEY,
  customer_id TEXT NOT NULL REFERENCES customers(id),
  project TEXT NOT NULL,
  key_id TEXT NOT NULL UNIQUE,
  public_key_spki TEXT NOT NULL,
  label TEXT NOT NULL DEFAULT '',
  provider_reported TEXT NOT NULL DEFAULT '',
  assurance TEXT NOT NULL DEFAULT 'proof_verified' CHECK (assurance IN ('proof_verified', 'hardware_attested')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  revision INTEGER NOT NULL DEFAULT 0 CHECK (revision = CAST(revision AS BIGINT) AND revision BETWEEN 0 AND 9007199254740991),
  created_at INTEGER NOT NULL CHECK (created_at = CAST(created_at AS BIGINT) AND created_at BETWEEN 0 AND 9007199254740991),
  last_proof_at INTEGER NOT NULL CHECK (last_proof_at = CAST(last_proof_at AS BIGINT) AND last_proof_at BETWEEN 0 AND 9007199254740991)
);

CREATE TABLE IF NOT EXISTS device_bound_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  invocation_id TEXT NOT NULL UNIQUE,
  binding_id TEXT NOT NULL REFERENCES device_bound_bindings(id),
  customer_id TEXT NOT NULL REFERENCES customers(id),
  event_type TEXT NOT NULL CHECK (event_type IN ('exchange', 'renew', 'retire')),
  actor TEXT NOT NULL,
  occurred_at INTEGER NOT NULL CHECK (occurred_at = CAST(occurred_at AS BIGINT) AND occurred_at BETWEEN 0 AND 9007199254740991)
);

CREATE TABLE IF NOT EXISTS device_bound_leases (
  id TEXT NOT NULL PRIMARY KEY,
  binding_id TEXT NOT NULL REFERENCES device_bound_bindings(id),
  generation INTEGER NOT NULL CHECK (generation = CAST(generation AS BIGINT) AND generation BETWEEN 1 AND 9007199254740991),
  entitlement_revision INTEGER NOT NULL CHECK (entitlement_revision = CAST(entitlement_revision AS BIGINT) AND entitlement_revision BETWEEN 0 AND 9007199254740991),
  invocation_id TEXT NOT NULL UNIQUE,
  issued_at INTEGER NOT NULL CHECK (issued_at = CAST(issued_at AS BIGINT) AND issued_at BETWEEN 0 AND 9007199254740991),
  expires_at INTEGER NOT NULL CHECK (expires_at = CAST(expires_at AS BIGINT) AND expires_at > issued_at AND expires_at - issued_at <= 86400),
  accept_until INTEGER NOT NULL CHECK (accept_until = CAST(accept_until AS BIGINT) AND accept_until = expires_at + 120 AND accept_until <= 9007199254740991),
  token TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS device_bound_operations (
  key_id TEXT NOT NULL,
  purpose TEXT NOT NULL CHECK (purpose IN ('exchange', 'renew', 'retire')),
  operation_id TEXT NOT NULL,
  invocation_id TEXT NOT NULL UNIQUE,
  request_digest TEXT NOT NULL,
  customer_id TEXT NOT NULL REFERENCES customers(id),
  binding_id TEXT NOT NULL,
  lease_id TEXT,
  status TEXT NOT NULL DEFAULT 'prepared' CHECK (status IN ('prepared', 'complete')),
  response_json TEXT NOT NULL,
  committed_at INTEGER NOT NULL CHECK (committed_at = CAST(committed_at AS BIGINT) AND committed_at BETWEEN 0 AND 9007199254740991),
  retain_until INTEGER NOT NULL CHECK (retain_until = CAST(retain_until AS BIGINT) AND retain_until > committed_at AND retain_until <= 9007199254740991),
  PRIMARY KEY (key_id, purpose, operation_id)
);

CREATE TABLE IF NOT EXISTS entitlement_devices (
  project TEXT NOT NULL,
  feature TEXT NOT NULL,
  license_fingerprint TEXT NOT NULL,
  device_key_id TEXT NOT NULL,
  public_key_spki_der_base64 TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('active', 'revoked', 'disabled')),
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  last_seen_at INTEGER NULL,
  notes TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (project, feature, license_fingerprint, device_key_id),
  FOREIGN KEY (project, feature, license_fingerprint)
    REFERENCES entitlements(project, feature, license_fingerprint)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "entitlement_events" (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project TEXT NOT NULL,
  feature TEXT NOT NULL,
  license_fingerprint TEXT NOT NULL,
  device_hash TEXT NOT NULL DEFAULT '',
  event_type TEXT NOT NULL CHECK (event_type IN ('create', 'update', 'disable', 'reenable', 'revoke', 'upsert', 'revoked-override')),
  status TEXT NOT NULL CHECK (status IN ('active', 'revoked', 'disabled')),
  revocation_seq INTEGER NOT NULL,
  detail TEXT NOT NULL DEFAULT '',
  actor TEXT NOT NULL DEFAULT '',
  actor_type TEXT NOT NULL DEFAULT 'unknown' CHECK (actor_type IN ('access', 'dev', 'cli', 'sync', 'system', 'unknown')),
  source TEXT NOT NULL DEFAULT 'admin',
  request_id TEXT NOT NULL DEFAULT '',
  ip TEXT NOT NULL DEFAULT '',
  prev_json TEXT NOT NULL DEFAULT '',
  next_json TEXT NOT NULL DEFAULT '',
  reason TEXT NOT NULL DEFAULT '',
  idempotency_key TEXT NULL,
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS entitlement_policies (
  id                          TEXT PRIMARY KEY,
  project                     TEXT NOT NULL,
  name                        TEXT NOT NULL,
  type                        TEXT NOT NULL CHECK (type IN ('trial', 'node_locked', 'floating', 'subscription')),
  status                      TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  valid_from_offset_sec       INTEGER NULL,
  duration_sec                INTEGER NULL,
  assertion_ttl_seconds       INTEGER NOT NULL DEFAULT 300,
  pool_size                   INTEGER NOT NULL DEFAULT 0,
  max_active_devices          INTEGER NOT NULL DEFAULT 1,
  max_borrow_sec              INTEGER NOT NULL DEFAULT 0,
  expiry_strategy             TEXT NOT NULL DEFAULT 'fixed_window' CHECK (expiry_strategy IN ('fixed_window', 'non_expiring')),
  trial_expiration_basis      TEXT NOT NULL DEFAULT 'from_issue' CHECK (trial_expiration_basis IN ('from_issue', 'from_first_activation', 'from_first_use')),
  trial_duration_sec          INTEGER NOT NULL DEFAULT 0,
  trial_one_per_device        INTEGER NOT NULL DEFAULT 0,
  trial_require_device_proof  INTEGER NOT NULL DEFAULT 0,
  notes                       TEXT NOT NULL DEFAULT '',
  created_at                  INTEGER NOT NULL,
  updated_at                  INTEGER NOT NULL
, meter_quota INTEGER NOT NULL DEFAULT 0, meter_period_sec INTEGER NOT NULL DEFAULT 2592000);

CREATE TABLE IF NOT EXISTS entitlements (
  project TEXT NOT NULL,
  feature TEXT NOT NULL,
  license_fingerprint TEXT NOT NULL,
  device_hash TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL CHECK (status IN ('active', 'revoked', 'disabled')),
  assertion_ttl_seconds INTEGER NOT NULL DEFAULT 300,
  cache_ttl_seconds INTEGER NOT NULL DEFAULT 3600,
  revocation_seq INTEGER NOT NULL DEFAULT 0,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL, valid_from INTEGER NULL, valid_until INTEGER NULL, notes TEXT NOT NULL DEFAULT '', customer_id TEXT NULL, license_id TEXT NULL, max_active_devices INTEGER NOT NULL DEFAULT 1, lease_seconds INTEGER NOT NULL DEFAULT 2592000, rebind_window_sec INTEGER NOT NULL DEFAULT 7776000, pool_size INTEGER NOT NULL DEFAULT 0, heartbeat_grace_sec INTEGER NOT NULL DEFAULT 900, max_borrow_sec INTEGER NOT NULL DEFAULT 0, allow_overdraft INTEGER NOT NULL DEFAULT 0, last_applied_order_seq INTEGER NOT NULL DEFAULT 0, last_applied_order_epoch INTEGER NOT NULL DEFAULT 0, policy_id TEXT NULL, is_trial INTEGER NOT NULL DEFAULT 0, trial_expiration_basis TEXT NULL, trial_duration_sec INTEGER NOT NULL DEFAULT 0, trial_one_per_device INTEGER NOT NULL DEFAULT 0, trial_require_device_proof INTEGER NOT NULL DEFAULT 0, trial_started_at INTEGER NULL, trial_device_hash TEXT NULL, meter_quota INTEGER NOT NULL DEFAULT 0, meter_period_sec INTEGER NOT NULL DEFAULT 2592000, enforcement_mode TEXT NOT NULL DEFAULT 'legacy'
  CHECK (enforcement_mode IN ('legacy', 'device_bound_v1')), authority_revision INTEGER NOT NULL DEFAULT 0
  CHECK (authority_revision = CAST(authority_revision AS BIGINT) AND authority_revision BETWEEN 0 AND 9007199254740991),
  PRIMARY KEY (project, feature, license_fingerprint)
);

CREATE TABLE IF NOT EXISTS lease_issuance (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project TEXT NOT NULL,
  feature TEXT NOT NULL,
  license_fingerprint TEXT NOT NULL,
  device_key_id TEXT NOT NULL,
  lease_key_id TEXT NOT NULL,
  issued_at INTEGER NOT NULL,
  valid_from INTEGER NOT NULL,
  valid_to INTEGER NOT NULL,
  request_id TEXT NULL,
  FOREIGN KEY (project, feature, license_fingerprint)
    REFERENCES entitlements(project, feature, license_fingerprint) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS license_plan_assignment_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  license_id TEXT NOT NULL,
  project TEXT NOT NULL,
  plan_id TEXT NOT NULL,
  license_fingerprint TEXT NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('create', 'update')),
  actor TEXT NOT NULL DEFAULT '',
  actor_type TEXT NOT NULL DEFAULT 'unknown' CHECK (actor_type IN ('access', 'dev', 'cli', 'sync', 'system', 'unknown')),
  source TEXT NOT NULL DEFAULT 'admin',
  request_id TEXT NOT NULL DEFAULT '',
  prev_json TEXT NOT NULL DEFAULT '',
  next_json TEXT NOT NULL DEFAULT '',
  reason TEXT NOT NULL DEFAULT '',
  idempotency_key TEXT NULL,
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS license_plan_assignments (
  license_id TEXT NOT NULL,
  project TEXT NOT NULL,
  plan_id TEXT NOT NULL,
  license_fingerprint TEXT NOT NULL,
  customer_id TEXT NULL,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled', 'revoked')),
  support_until INTEGER NULL,
  addons_json TEXT NOT NULL DEFAULT '[]',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  PRIMARY KEY (license_id, project),
  FOREIGN KEY (project, plan_id) REFERENCES catalog_plans(project, id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS license_plan_projection_generations (
  scope TEXT PRIMARY KEY CHECK (scope = 'catalog'),
  generation INTEGER NOT NULL DEFAULT 0,
  updated_at INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS license_plan_projection_previews (
  id TEXT PRIMARY KEY,
  actor_subject TEXT NOT NULL,
  source_generation INTEGER NOT NULL,
  normalized_input_json TEXT NOT NULL,
  projection_json TEXT NOT NULL,
  actions_json TEXT NOT NULL,
  effective_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL,
  claim_token TEXT NULL,
  claimed_at INTEGER NULL,
  consumed_at INTEGER NULL,
  applied_response_json TEXT NULL,
  created_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS licenses (
  id TEXT PRIMARY KEY,
  customer_id TEXT NULL,
  project TEXT NOT NULL,
  label TEXT NOT NULL DEFAULT '',
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS mutation_idempotency (
  scope TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  response_json TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  PRIMARY KEY (scope, idempotency_key)
);

CREATE TABLE IF NOT EXISTS order_events (
  event_id        TEXT NOT NULL,
  subscription_id TEXT NOT NULL,
  project         TEXT NOT NULL,
  feature         TEXT NOT NULL,
  order_epoch     INTEGER NOT NULL,
  seq             INTEGER NOT NULL,
  intent          TEXT NOT NULL,
  key_id          TEXT NOT NULL,
  payload_digest  TEXT NOT NULL,
  raw_payload     TEXT NOT NULL,
  status          TEXT NOT NULL CHECK (status IN ('accepted', 'processed', 'superseded', 'rejected')),
  result_json     TEXT NOT NULL DEFAULT '',
  received_at     INTEGER NOT NULL,
  processed_at    INTEGER NULL,
  PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS order_ingest_nonces (
  key_id      TEXT NOT NULL,
  event_id    TEXT NOT NULL,
  timestamp   INTEGER NOT NULL,
  consumed_at INTEGER NOT NULL,
  expires_at  INTEGER NOT NULL,
  PRIMARY KEY (key_id, event_id)
);

CREATE TABLE IF NOT EXISTS orders (
  subscription_id     TEXT NOT NULL,
  project             TEXT NOT NULL,
  feature             TEXT NOT NULL,
  license_fingerprint TEXT NOT NULL,
  customer_id         TEXT NULL,
  license_id          TEXT NULL,
  last_seq            INTEGER NOT NULL DEFAULT 0,
  order_epoch         INTEGER NOT NULL DEFAULT 0,
  fingerprint_origin  TEXT NOT NULL DEFAULT 'derived' CHECK (fingerprint_origin IN ('derived', 'supplied')),
  created_at          INTEGER NOT NULL,
  updated_at          INTEGER NOT NULL,
  PRIMARY KEY (subscription_id, project, feature)
);

CREATE TABLE IF NOT EXISTS policy_events (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  policy_id   TEXT NOT NULL,
  project     TEXT NOT NULL,
  event_type  TEXT NOT NULL CHECK (event_type IN ('create', 'update', 'disable', 'reenable')),
  actor       TEXT NOT NULL DEFAULT '',
  actor_type  TEXT NOT NULL DEFAULT 'unknown' CHECK (actor_type IN ('access', 'dev', 'cli', 'sync', 'system', 'unknown')),
  source      TEXT NOT NULL DEFAULT 'admin',
  reason      TEXT NOT NULL DEFAULT '',
  request_id  TEXT NOT NULL DEFAULT '',
  prev_json   TEXT NOT NULL DEFAULT '',
  next_json   TEXT NOT NULL DEFAULT '',
  created_at  INTEGER NOT NULL,
  FOREIGN KEY (policy_id) REFERENCES entitlement_policies(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS portal_bootstrap_events (
  id          TEXT PRIMARY KEY,
  customer_id TEXT NOT NULL,
  email_lower TEXT NOT NULL,
  actor       TEXT NOT NULL DEFAULT '',
  created_at  INTEGER NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS portal_identities (
  provider TEXT NOT NULL CHECK (provider IN ('google', 'github')),
  subject TEXT NOT NULL,
  customer_id TEXT NOT NULL REFERENCES customers(id),
  email TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  PRIMARY KEY (provider, subject),
  UNIQUE (customer_id, provider)
);

CREATE TABLE IF NOT EXISTS portal_oauth_states (
  state_hash TEXT PRIMARY KEY,
  provider TEXT NOT NULL CHECK (provider IN ('google', 'github')),
  browser_hash TEXT NOT NULL,
  nonce TEXT NOT NULL,
  link_session_id TEXT REFERENCES portal_sessions(id) ON DELETE CASCADE,
  expires_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS portal_otp (
  id            TEXT PRIMARY KEY,
  customer_id   TEXT NOT NULL,
  email_lower   TEXT NOT NULL,
  secret_hmac   TEXT NOT NULL,
  code_hmac     TEXT NOT NULL,
  pepper_key_id TEXT NOT NULL,
  attempt_count INTEGER NOT NULL DEFAULT 0,
  consumed_at   INTEGER NULL,
  expires_at    INTEGER NOT NULL,
  created_at    INTEGER NOT NULL,
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS portal_passwords (
  customer_id TEXT PRIMARY KEY NOT NULL REFERENCES customers(id),
  email_lower TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS portal_sessions (
  id               TEXT PRIMARY KEY,
  customer_id      TEXT NOT NULL,
  session_hmac     TEXT NOT NULL,
  pepper_key_id    TEXT NOT NULL,
  account_token_id TEXT NULL,
  status           TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
  user_agent       TEXT NOT NULL DEFAULT '',
  created_at       INTEGER NOT NULL,
  last_used_at     INTEGER NULL,
  expires_at       INTEGER NOT NULL, auth_method TEXT NOT NULL DEFAULT 'legacy'
  CHECK (auth_method IN ('legacy', 'otp', 'oauth', 'password')),
  FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
  FOREIGN KEY (account_token_id) REFERENCES account_tokens(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS rate_limit_counters (
  namespace TEXT NOT NULL,
  rate_key TEXT NOT NULL,
  window_start INTEGER NOT NULL,
  request_count INTEGER NOT NULL,
  expires_at INTEGER NOT NULL,
  updated_at INTEGER NOT NULL,
  PRIMARY KEY (namespace, rate_key, window_start)
);

CREATE TABLE IF NOT EXISTS request_proof_nonces (
  project TEXT NOT NULL,
  feature TEXT NOT NULL,
  license_fingerprint TEXT NOT NULL,
  device_key_id TEXT NOT NULL,
  nonce TEXT NOT NULL,
  request_timestamp INTEGER NOT NULL,
  consumed_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL,
  PRIMARY KEY (project, feature, license_fingerprint, device_key_id, nonce)
);

CREATE TABLE IF NOT EXISTS seat_checkouts (
  project TEXT NOT NULL,
  feature TEXT NOT NULL,
  license_fingerprint TEXT NOT NULL,
  seat_id TEXT NOT NULL,
  client_instance_id TEXT NOT NULL,
  mode TEXT NOT NULL CHECK (mode IN ('live', 'borrowed')),
  checked_out_at INTEGER NOT NULL,
  heartbeat_deadline INTEGER NOT NULL,
  PRIMARY KEY (project, feature, license_fingerprint, seat_id),
  FOREIGN KEY (project, feature, license_fingerprint)
    REFERENCES entitlements(project, feature, license_fingerprint) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS usage_events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project TEXT NOT NULL,
  feature TEXT NOT NULL,
  license_fingerprint TEXT NOT NULL,
  event_type TEXT NOT NULL CHECK (event_type IN ('checkout', 'release', 'reclaim', 'denied')),
  seat_id TEXT NULL,
  device_key_id TEXT NULL,
  reason TEXT NULL,
  ts INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS usage_meters (
  project             TEXT    NOT NULL,
  feature             TEXT    NOT NULL,
  license_fingerprint TEXT    NOT NULL,
  period_start        INTEGER NOT NULL,
  units_consumed      INTEGER NOT NULL DEFAULT 0,
  updated_at          INTEGER NOT NULL,
  PRIMARY KEY (project, feature, license_fingerprint, period_start)
);

CREATE TABLE IF NOT EXISTS webhook_cursor (
  event_source TEXT PRIMARY KEY,
  last_id      INTEGER NOT NULL DEFAULT 0,
  updated_at   INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS webhook_deliveries (
  id              INTEGER PRIMARY KEY AUTOINCREMENT,
  endpoint_id     TEXT NOT NULL,
  event_source    TEXT NOT NULL CHECK (event_source IN ('entitlement', 'customer', 'order')),
  event_id        INTEGER NOT NULL,
  event_type      TEXT NOT NULL DEFAULT '',
  payload_json    TEXT NOT NULL DEFAULT '',
  status          TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'delivered', 'failed')),
  attempts        INTEGER NOT NULL DEFAULT 0,
  last_status     INTEGER NOT NULL DEFAULT 0,
  last_error      TEXT NOT NULL DEFAULT '',
  next_attempt_at INTEGER NOT NULL DEFAULT 0,
  created_at      INTEGER NOT NULL,
  delivered_at    INTEGER NULL,
  UNIQUE (endpoint_id, event_source, event_id)
);

CREATE TABLE IF NOT EXISTS webhook_endpoints (
  id          TEXT PRIMARY KEY,
  url         TEXT NOT NULL,
  event_types TEXT NOT NULL DEFAULT '',
  status      TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  description TEXT NOT NULL DEFAULT '',
  created_at  INTEGER NOT NULL,
  updated_at  INTEGER NOT NULL
, scope_project TEXT, scope_customer_id TEXT);

CREATE TABLE IF NOT EXISTS webhook_events (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  endpoint_id TEXT NOT NULL,
  event_type  TEXT NOT NULL CHECK (event_type IN ('disable', 'reenable')),
  prev_status TEXT NOT NULL,
  next_status TEXT NOT NULL,
  actor       TEXT NOT NULL DEFAULT '',
  actor_type  TEXT NOT NULL DEFAULT 'unknown' CHECK (actor_type IN ('access', 'dev', 'cli', 'sync', 'system', 'unknown')),
  source      TEXT NOT NULL DEFAULT 'admin',
  reason      TEXT NOT NULL DEFAULT '',
  request_id  TEXT NOT NULL DEFAULT '',
  created_at  INTEGER NOT NULL,
  FOREIGN KEY (endpoint_id) REFERENCES webhook_endpoints(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_account_token_events_customer ON account_token_events(customer_id);

CREATE INDEX IF NOT EXISTS idx_account_token_events_token ON account_token_events(account_token_id);

CREATE INDEX IF NOT EXISTS idx_account_tokens_customer ON account_tokens(customer_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_account_tokens_hmac ON account_tokens(token_hmac);

CREATE INDEX IF NOT EXISTS idx_account_tokens_status ON account_tokens(status);

CREATE INDEX IF NOT EXISTS idx_audit_digests_source ON audit_digests(source, id);

CREATE INDEX IF NOT EXISTS idx_bound_approval_cleanup
ON device_bound_authorizations(code_expires_at)
WHERE approval_ciphertext IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_bound_authorizations_expiry ON device_bound_authorizations(expires_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_bound_bindings_active_device
  ON device_bound_bindings(project, feature, license_fingerprint, device_id) WHERE state = 'active';

CREATE INDEX IF NOT EXISTS idx_bound_bindings_capacity ON device_bound_bindings(project, feature, license_fingerprint, state, hold_until);

CREATE INDEX IF NOT EXISTS idx_bound_bindings_device ON device_bound_bindings(device_id, state);

CREATE INDEX IF NOT EXISTS idx_bound_challenges_expiry ON device_bound_challenges(expires_at);

CREATE INDEX IF NOT EXISTS idx_bound_consumed_attempt_cleanup ON device_bound_authorizations(recovery_until)
WHERE status='consumed';

CREATE INDEX IF NOT EXISTS idx_bound_devices_customer ON device_bound_devices(customer_id, project, id);

CREATE INDEX IF NOT EXISTS idx_bound_events_customer ON device_bound_events(customer_id, id);

CREATE INDEX IF NOT EXISTS idx_bound_lease_cleanup ON device_bound_leases(accept_until);

CREATE INDEX IF NOT EXISTS idx_bound_leases_binding_expiry ON device_bound_leases(binding_id, accept_until);

CREATE INDEX IF NOT EXISTS idx_bound_operation_payload_cleanup ON device_bound_operations(retain_until)
WHERE status='complete' AND response_json<>'';

CREATE INDEX IF NOT EXISTS idx_bound_operations_retention ON device_bound_operations(retain_until);

CREATE INDEX IF NOT EXISTS idx_bound_unconsumed_attempt_cleanup ON device_bound_authorizations(expires_at)
WHERE status IN ('pending','approved','denied');

CREATE INDEX IF NOT EXISTS idx_catalog_events_entity
  ON catalog_events(entity_type, entity_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_catalog_events_project
  ON catalog_events(project, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_catalog_features_project_status
  ON catalog_features(project, status);

CREATE INDEX IF NOT EXISTS idx_catalog_import_previews_consumed
  ON catalog_import_previews(consumed_at)
  WHERE consumed_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_catalog_import_previews_expiry
  ON catalog_import_previews(expires_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_catalog_plan_features_addon
  ON catalog_plan_features(plan_id, addon_key)
  WHERE addon_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_catalog_plan_features_project
  ON catalog_plan_features(project, plan_id, status);

CREATE INDEX IF NOT EXISTS idx_catalog_plans_project_status
  ON catalog_plans(project, status);

CREATE INDEX IF NOT EXISTS idx_customer_events_customer ON customer_events(customer_id, created_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_email
  ON customers(lower(email))
  WHERE email <> '';

CREATE INDEX IF NOT EXISTS idx_entitlement_devices_entitlement
  ON entitlement_devices(project, feature, license_fingerprint);

CREATE INDEX IF NOT EXISTS idx_entitlement_devices_status
  ON entitlement_devices(status);

CREATE INDEX IF NOT EXISTS idx_entitlement_events_actor
  ON entitlement_events(actor, created_at);

CREATE INDEX IF NOT EXISTS idx_entitlement_events_lookup
  ON entitlement_events(project, feature, license_fingerprint, created_at);

CREATE INDEX IF NOT EXISTS idx_entitlement_events_request
  ON entitlement_events(request_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_entitlement_policies_name ON entitlement_policies(project, lower(name));

CREATE INDEX IF NOT EXISTS idx_entitlements_customer
  ON entitlements(customer_id);

CREATE INDEX IF NOT EXISTS idx_entitlements_customer_project
  ON entitlements(customer_id, project, feature, license_fingerprint);

CREATE INDEX IF NOT EXISTS idx_entitlements_license
  ON entitlements(license_id);

CREATE INDEX IF NOT EXISTS idx_entitlements_project_feature_status
  ON entitlements(project, feature, status);

CREATE INDEX IF NOT EXISTS idx_entitlements_project_license_fingerprint
  ON entitlements(project, license_id, license_fingerprint);

CREATE INDEX IF NOT EXISTS idx_entitlements_status
  ON entitlements(status);

CREATE INDEX IF NOT EXISTS idx_entitlements_valid_until
  ON entitlements(valid_until);

CREATE INDEX IF NOT EXISTS idx_lease_issuance_entitlement
  ON lease_issuance(project, feature, license_fingerprint, issued_at);

CREATE INDEX IF NOT EXISTS idx_lease_issuance_issued_at
  ON lease_issuance(issued_at);

CREATE INDEX IF NOT EXISTS idx_license_plan_assignment_events_assignment
  ON license_plan_assignment_events(license_id, project, id DESC);

CREATE INDEX IF NOT EXISTS idx_license_plan_assignments_customer
  ON license_plan_assignments(customer_id);

CREATE INDEX IF NOT EXISTS idx_license_plan_assignments_plan
  ON license_plan_assignments(project, plan_id, status);

CREATE INDEX IF NOT EXISTS idx_license_plan_projection_previews_expiry_id
  ON license_plan_projection_previews(expires_at, id);

CREATE INDEX IF NOT EXISTS idx_licenses_customer
  ON licenses(customer_id);

CREATE INDEX IF NOT EXISTS idx_licenses_project
  ON licenses(project);

CREATE INDEX IF NOT EXISTS idx_mutation_idempotency_created_at
  ON mutation_idempotency(created_at);

CREATE INDEX IF NOT EXISTS idx_order_events_sub_seq
  ON order_events(subscription_id, project, feature, order_epoch, seq);

CREATE INDEX IF NOT EXISTS idx_order_events_unprocessed
  ON order_events(subscription_id, project, feature, status);

CREATE INDEX IF NOT EXISTS idx_order_ingest_nonces_expires_at
  ON order_ingest_nonces(expires_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_fp_unique
  ON orders(project, feature, license_fingerprint);

CREATE INDEX IF NOT EXISTS idx_policy_events_policy ON policy_events(policy_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_portal_bootstrap_customer ON portal_bootstrap_events(customer_id);

CREATE INDEX IF NOT EXISTS idx_portal_oauth_states_expires ON portal_oauth_states(expires_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_portal_otp_code ON portal_otp(code_hmac);

CREATE INDEX IF NOT EXISTS idx_portal_otp_expires ON portal_otp(expires_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_portal_otp_secret ON portal_otp(secret_hmac);

CREATE INDEX IF NOT EXISTS idx_portal_sessions_customer ON portal_sessions(customer_id);

CREATE INDEX IF NOT EXISTS idx_portal_sessions_expires ON portal_sessions(expires_at);

CREATE UNIQUE INDEX IF NOT EXISTS idx_portal_sessions_hmac ON portal_sessions(session_hmac);

CREATE INDEX IF NOT EXISTS idx_rate_limit_counters_expires_at
  ON rate_limit_counters(expires_at);

CREATE INDEX IF NOT EXISTS idx_request_proof_nonces_expires_at
  ON request_proof_nonces(expires_at);

CREATE INDEX IF NOT EXISTS idx_seat_checkouts_live
  ON seat_checkouts(project, feature, license_fingerprint, heartbeat_deadline);

CREATE INDEX IF NOT EXISTS idx_usage_events_ts
  ON usage_events(ts);

CREATE INDEX IF NOT EXISTS idx_usage_events_window
  ON usage_events(project, feature, license_fingerprint, ts);

CREATE INDEX IF NOT EXISTS idx_usage_meters_entitlement
  ON usage_meters(project, feature, license_fingerprint);

CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_due
  ON webhook_deliveries(status, next_attempt_at);

CREATE INDEX IF NOT EXISTS idx_webhook_endpoints_status ON webhook_endpoints(status);

CREATE INDEX IF NOT EXISTS idx_webhook_events_endpoint ON webhook_events(endpoint_id, created_at DESC);

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_assignments_delete
AFTER DELETE ON license_plan_assignments
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_assignments_insert
AFTER INSERT ON license_plan_assignments
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_assignments_update
AFTER UPDATE ON license_plan_assignments
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_catalog_features_delete
AFTER DELETE ON catalog_features
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_catalog_features_insert
AFTER INSERT ON catalog_features
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_catalog_features_update
AFTER UPDATE ON catalog_features
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_catalog_plan_features_delete
AFTER DELETE ON catalog_plan_features
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_catalog_plan_features_insert
AFTER INSERT ON catalog_plan_features
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_catalog_plan_features_update
AFTER UPDATE ON catalog_plan_features
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_catalog_plans_delete
AFTER DELETE ON catalog_plans
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_catalog_plans_insert
AFTER INSERT ON catalog_plans
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_catalog_plans_update
AFTER UPDATE ON catalog_plans
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_entitlement_policies_delete
AFTER DELETE ON entitlement_policies
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_entitlement_policies_insert
AFTER INSERT ON entitlement_policies
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_entitlement_policies_update
AFTER UPDATE ON entitlement_policies
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_entitlements_delete
AFTER DELETE ON entitlements
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_entitlements_insert
AFTER INSERT ON entitlements
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS bump_license_plan_projection_generation_entitlements_update
AFTER UPDATE ON entitlements
BEGIN
  UPDATE license_plan_projection_generations
  SET generation = generation + 1,
      updated_at = CAST(strftime('%s', 'now') AS INTEGER)
  WHERE scope = 'catalog';
END;

CREATE TRIGGER IF NOT EXISTS tr_bound_attempt_approval_immutable BEFORE UPDATE OF customer_id,feature,license_fingerprint,code_hash,code_expires_at ON device_bound_authorizations
WHEN OLD.status IN ('approved','consumed') AND (NEW.customer_id IS NOT OLD.customer_id
  OR NEW.feature IS NOT OLD.feature OR NEW.license_fingerprint IS NOT OLD.license_fingerprint
  OR NEW.code_hash IS NOT OLD.code_hash OR NEW.code_expires_at IS NOT OLD.code_expires_at)
BEGIN SELECT RAISE(ABORT, 'authorization_approval_immutable'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_attempt_consumption_immutable BEFORE UPDATE OF consumed_invocation_id,consumed_operation_id,recovery_until ON device_bound_authorizations
WHEN OLD.status='consumed' AND (NEW.consumed_invocation_id IS NOT OLD.consumed_invocation_id
  OR NEW.consumed_operation_id IS NOT OLD.consumed_operation_id OR NEW.recovery_until IS NOT OLD.recovery_until)
BEGIN SELECT RAISE(ABORT, 'authorization_consumption_immutable'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_attempt_intent_immutable BEFORE UPDATE OF handle_hash,client_id,project,key_id,public_key_spki,redirect_uri,client_state,pkce_challenge,created_at,expires_at ON device_bound_authorizations
WHEN NEW.handle_hash IS NOT OLD.handle_hash OR NEW.client_id IS NOT OLD.client_id
  OR NEW.project IS NOT OLD.project OR NEW.key_id IS NOT OLD.key_id OR NEW.public_key_spki IS NOT OLD.public_key_spki
  OR NEW.redirect_uri IS NOT OLD.redirect_uri OR NEW.client_state IS NOT OLD.client_state
  OR NEW.pkce_challenge IS NOT OLD.pkce_challenge OR NEW.created_at IS NOT OLD.created_at OR NEW.expires_at IS NOT OLD.expires_at
BEGIN SELECT RAISE(ABORT, 'authorization_intent_immutable'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_attempt_revision_no_reset BEFORE UPDATE OF revision ON device_bound_authorizations
WHEN NEW.revision < OLD.revision
BEGIN SELECT RAISE(ABORT, 'authorization_revision_cannot_shrink'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_attempt_terminal BEFORE UPDATE OF status ON device_bound_authorizations
WHEN NEW.status != OLD.status AND NOT ((OLD.status='pending' AND NEW.status IN ('approved','denied'))
  OR (OLD.status='approved' AND NEW.status='consumed'))
BEGIN SELECT RAISE(ABORT, 'authorization_transition_invalid'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_binding_hold_monotonic BEFORE UPDATE OF hold_until ON device_bound_bindings
WHEN NEW.hold_until < OLD.hold_until
BEGIN SELECT RAISE(ABORT, 'binding_hold_cannot_shrink'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_binding_identity_immutable BEFORE UPDATE OF id, project, feature, license_fingerprint, device_id ON device_bound_bindings
WHEN NEW.id IS NOT OLD.id OR NEW.project IS NOT OLD.project OR NEW.feature IS NOT OLD.feature
  OR NEW.license_fingerprint IS NOT OLD.license_fingerprint OR NEW.device_id IS NOT OLD.device_id
BEGIN SELECT RAISE(ABORT, 'binding_identity_immutable'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_binding_keep_tombstone BEFORE DELETE ON device_bound_bindings
BEGIN SELECT RAISE(ABORT, 'binding_tombstone_required'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_binding_no_early_release BEFORE UPDATE OF state ON device_bound_bindings
WHEN NEW.state = 'released' AND (OLD.state = 'active' OR OLD.hold_until > unixepoch())
BEGIN SELECT RAISE(ABORT, 'binding_hold_active'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_binding_no_resurrection BEFORE UPDATE OF state ON device_bound_bindings
WHEN (OLD.state = 'retiring' AND NEW.state = 'active') OR (OLD.state = 'released' AND NEW.state != 'released')
BEGIN SELECT RAISE(ABORT, 'binding_retirement_terminal'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_binding_revision_no_reset BEFORE UPDATE OF revision,generation ON device_bound_bindings
WHEN NEW.revision < OLD.revision OR NEW.generation < OLD.generation
BEGIN SELECT RAISE(ABORT, 'binding_revision_cannot_shrink'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_capacity_decrease BEFORE UPDATE OF max_active_devices ON entitlements
WHEN NEW.enforcement_mode = 'device_bound_v1' AND NEW.max_active_devices < (
  SELECT COUNT(*) FROM device_bound_bindings b WHERE b.project = OLD.project
  AND b.feature = OLD.feature AND b.license_fingerprint = OLD.license_fingerprint
  AND (b.state = 'active' OR (b.state = 'retiring' AND b.hold_until > unixepoch()))
)
BEGIN SELECT RAISE(ABORT, 'capacity_in_use'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_challenge_immutable BEFORE UPDATE ON device_bound_challenges
WHEN NEW.id IS NOT OLD.id OR NEW.purpose IS NOT OLD.purpose OR NEW.subject_id IS NOT OLD.subject_id
  OR NEW.key_id IS NOT OLD.key_id OR NEW.operation_id IS NOT OLD.operation_id OR NEW.nonce_hash IS NOT OLD.nonce_hash
  OR NEW.created_at IS NOT OLD.created_at OR NEW.expires_at IS NOT OLD.expires_at
  OR OLD.consumed_invocation_id IS NOT NULL OR NEW.consumed_invocation_id IS NULL
BEGIN SELECT RAISE(ABORT, 'challenge_immutable'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_customer_revision AFTER UPDATE OF status ON customers
WHEN NEW.status IS NOT OLD.status
BEGIN UPDATE customers SET authority_revision=OLD.authority_revision+1 WHERE id=NEW.id; END;

CREATE TRIGGER IF NOT EXISTS tr_bound_customer_revision_no_reset BEFORE UPDATE OF authority_revision ON customers
WHEN NEW.authority_revision < OLD.authority_revision
BEGIN SELECT RAISE(ABORT, 'authority_revision_cannot_shrink'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_device_disable AFTER UPDATE OF status ON device_bound_devices
WHEN NEW.status != OLD.status
BEGIN
  UPDATE device_bound_devices SET revision=OLD.revision+1 WHERE id=NEW.id;
  UPDATE device_bound_bindings SET state='retiring',generation=generation+1,revision=revision+1,updated_at=unixepoch()
    WHERE device_id=NEW.id AND state='active' AND NEW.status='disabled';
END;

CREATE TRIGGER IF NOT EXISTS tr_bound_device_identity_immutable BEFORE UPDATE OF id, customer_id, project, key_id, public_key_spki ON device_bound_devices
WHEN NEW.id IS NOT OLD.id OR NEW.customer_id IS NOT OLD.customer_id OR NEW.project IS NOT OLD.project
  OR NEW.key_id IS NOT OLD.key_id OR NEW.public_key_spki IS NOT OLD.public_key_spki
BEGIN SELECT RAISE(ABORT, 'device_identity_immutable'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_device_keep_tombstone BEFORE DELETE ON device_bound_devices
BEGIN SELECT RAISE(ABORT, 'device_tombstone_required'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_device_revision_no_reset BEFORE UPDATE OF revision ON device_bound_devices
WHEN NEW.revision < OLD.revision
BEGIN SELECT RAISE(ABORT, 'device_revision_cannot_shrink'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_entitlement_revision AFTER UPDATE ON entitlements
WHEN NEW.status IS NOT OLD.status OR NEW.customer_id IS NOT OLD.customer_id
  OR NEW.valid_from IS NOT OLD.valid_from OR NEW.valid_until IS NOT OLD.valid_until
  OR NEW.max_active_devices IS NOT OLD.max_active_devices OR NEW.lease_seconds IS NOT OLD.lease_seconds
  OR NEW.enforcement_mode IS NOT OLD.enforcement_mode OR NEW.revocation_seq IS NOT OLD.revocation_seq
  OR NEW.pool_size IS NOT OLD.pool_size OR NEW.is_trial IS NOT OLD.is_trial
  OR NEW.trial_started_at IS NOT OLD.trial_started_at OR NEW.trial_duration_sec IS NOT OLD.trial_duration_sec
  OR NEW.trial_expiration_basis IS NOT OLD.trial_expiration_basis
  OR NEW.trial_one_per_device IS NOT OLD.trial_one_per_device
  OR NEW.trial_require_device_proof IS NOT OLD.trial_require_device_proof
  OR NEW.trial_device_hash IS NOT OLD.trial_device_hash
BEGIN
  UPDATE entitlements SET authority_revision = OLD.authority_revision + 1
  WHERE project = NEW.project AND feature = NEW.feature AND license_fingerprint = NEW.license_fingerprint;
END;

CREATE TRIGGER IF NOT EXISTS tr_bound_entitlement_revision_no_reset BEFORE UPDATE OF authority_revision ON entitlements
WHEN NEW.authority_revision < OLD.authority_revision
BEGIN SELECT RAISE(ABORT, 'authority_revision_cannot_shrink'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_mode_no_downgrade BEFORE UPDATE OF enforcement_mode ON entitlements
WHEN OLD.enforcement_mode = 'device_bound_v1' AND NEW.enforcement_mode != OLD.enforcement_mode
BEGIN SELECT RAISE(ABORT, 'protected_mode_downgrade'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_mode_requires_migration BEFORE UPDATE OF enforcement_mode ON entitlements
WHEN OLD.enforcement_mode = 'legacy' AND NEW.enforcement_mode = 'device_bound_v1'
BEGIN SELECT RAISE(ABORT, 'protected_mode_migration_required'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_operation_immutable BEFORE UPDATE ON device_bound_operations
WHEN NEW.key_id IS NOT OLD.key_id OR NEW.purpose IS NOT OLD.purpose
  OR NEW.operation_id IS NOT OLD.operation_id OR NEW.invocation_id IS NOT OLD.invocation_id
  OR NEW.request_digest IS NOT OLD.request_digest OR NEW.customer_id IS NOT OLD.customer_id
  OR NEW.binding_id IS NOT OLD.binding_id OR NEW.lease_id IS NOT OLD.lease_id
  OR NEW.committed_at IS NOT OLD.committed_at OR NEW.retain_until IS NOT OLD.retain_until
  OR NOT (
    (OLD.status='prepared' AND NEW.status='complete' AND NEW.response_json=OLD.response_json)
    OR (OLD.status='complete' AND NEW.status='complete' AND OLD.retain_until<=unixepoch() AND NEW.response_json='')
  )
BEGIN SELECT RAISE(ABORT, 'operation_result_immutable'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_operation_no_replace BEFORE INSERT ON device_bound_operations
WHEN EXISTS (SELECT 1 FROM device_bound_operations o WHERE
  (o.key_id=NEW.key_id AND o.purpose=NEW.purpose AND o.operation_id=NEW.operation_id)
  OR o.invocation_id=NEW.invocation_id)
BEGIN SELECT RAISE(ABORT, 'operation_tombstone_required'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_operation_tombstone BEFORE DELETE ON device_bound_operations
BEGIN SELECT RAISE(ABORT, 'operation_tombstone_required'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_owner_change BEFORE UPDATE OF customer_id ON entitlements
WHEN NEW.customer_id IS NOT OLD.customer_id AND EXISTS (
  SELECT 1 FROM device_bound_bindings b WHERE b.project = OLD.project
  AND b.feature = OLD.feature AND b.license_fingerprint = OLD.license_fingerprint
  AND (b.state = 'active' OR (b.state = 'retiring' AND b.hold_until > unixepoch()))
)
BEGIN SELECT RAISE(ABORT, 'capacity_in_use'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_reject_legacy_device_insert BEFORE INSERT ON entitlement_devices
WHEN EXISTS (SELECT 1 FROM entitlements e WHERE e.project = NEW.project AND e.feature = NEW.feature
  AND e.license_fingerprint = NEW.license_fingerprint AND e.enforcement_mode = 'device_bound_v1')
BEGIN SELECT RAISE(ABORT, 'legacy_protocol_disabled'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_reject_legacy_device_update BEFORE UPDATE ON entitlement_devices
WHEN EXISTS (SELECT 1 FROM entitlements e WHERE e.project = NEW.project AND e.feature = NEW.feature
  AND e.license_fingerprint = NEW.license_fingerprint AND e.enforcement_mode = 'device_bound_v1')
BEGIN SELECT RAISE(ABORT, 'legacy_protocol_disabled'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_reject_legacy_lease BEFORE INSERT ON lease_issuance
WHEN EXISTS (SELECT 1 FROM entitlements e WHERE e.project = NEW.project AND e.feature = NEW.feature
  AND e.license_fingerprint = NEW.license_fingerprint AND e.enforcement_mode = 'device_bound_v1')
BEGIN SELECT RAISE(ABORT, 'legacy_protocol_disabled'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_reject_legacy_seat_insert BEFORE INSERT ON seat_checkouts
WHEN EXISTS (SELECT 1 FROM entitlements e WHERE e.project = NEW.project AND e.feature = NEW.feature
  AND e.license_fingerprint = NEW.license_fingerprint AND e.enforcement_mode = 'device_bound_v1')
BEGIN SELECT RAISE(ABORT, 'legacy_protocol_disabled'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_reject_legacy_seat_update BEFORE UPDATE ON seat_checkouts
WHEN EXISTS (SELECT 1 FROM entitlements e WHERE e.project = NEW.project AND e.feature = NEW.feature
  AND e.license_fingerprint = NEW.license_fingerprint AND e.enforcement_mode = 'device_bound_v1')
BEGIN SELECT RAISE(ABORT, 'legacy_protocol_disabled'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_requested_feature_immutable BEFORE UPDATE OF requested_feature ON device_bound_authorizations
WHEN NEW.requested_feature IS NOT OLD.requested_feature
BEGIN SELECT RAISE(ABORT, 'authorization_intent_immutable'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_requested_feature_insert BEFORE INSERT ON device_bound_authorizations
WHEN NEW.requested_feature IS NOT NULL AND NEW.feature IS NOT NULL AND NEW.feature<>NEW.requested_feature
BEGIN SELECT RAISE(ABORT, 'authorization_feature_mismatch'); END;

CREATE TRIGGER IF NOT EXISTS tr_bound_requested_feature_update BEFORE UPDATE OF feature,requested_feature ON device_bound_authorizations
WHEN NEW.requested_feature IS NOT NULL AND NEW.feature IS NOT NULL AND NEW.feature<>NEW.requested_feature
BEGIN SELECT RAISE(ABORT, 'authorization_feature_mismatch'); END;
