include("${CMAKE_CURRENT_LIST_DIR}/../cmake/ReadReleaseManifest.cmake")

function(_lcc_read_manifest_numeric_define out_var public_key_header define_name)
	set(${out_var} "" PARENT_SCOPE)
	file(STRINGS "${public_key_header}" _lcc_numeric_lines
		REGEX "^[ \t]*#define[ \t]+${define_name}[ \t]+[^ \t]+[ \t]*$"
		LIMIT_COUNT 1)
	if(NOT _lcc_numeric_lines)
		return()
	endif()
	list(GET _lcc_numeric_lines 0 _lcc_numeric_line)
	string(REGEX REPLACE "^[ \t]*#define[ \t]+${define_name}[ \t]+([^ \t]+)[ \t]*$" "\\1"
		_lcc_numeric_value "${_lcc_numeric_line}")
	set(${out_var} "${_lcc_numeric_value}" PARENT_SCOPE)
endfunction()

function(_lcc_read_manifest_string_define out_var public_key_header define_name)
	set(${out_var} "" PARENT_SCOPE)
	file(STRINGS "${public_key_header}" _lcc_string_lines
		REGEX "^[ \t]*#define[ \t]+${define_name}[ \t]+\"[^\"]*\"[ \t]*$"
		LIMIT_COUNT 1)
	if(NOT _lcc_string_lines)
		return()
	endif()
	list(GET _lcc_string_lines 0 _lcc_string_line)
	string(REGEX REPLACE "^[ \t]*#define[ \t]+${define_name}[ \t]+\"([^\"]*)\"[ \t]*$" "\\1"
		_lcc_string_value "${_lcc_string_line}")
	set(${out_var} "${_lcc_string_value}" PARENT_SCOPE)
endfunction()

function(_lcc_read_manifest_public_key_der_len out_var public_key_header)
	_lcc_read_manifest_numeric_define(_lcc_public_key_len "${public_key_header}" PUBLIC_KEY_LEN)
	set(${out_var} "${_lcc_public_key_len}" PARENT_SCOPE)
endfunction()

function(lcc_assert_release_manifest prefix project_name project_magic expected_config description)
	if(ARGC GREATER 5)
		set(_expected_profile "${ARGV5}")
	else()
		set(_expected_profile "runtime")
	endif()

	set(_manifest "${prefix}/share/licensecc/${project_name}/release-manifest.cmake")
	if(NOT EXISTS "${_manifest}")
		message(FATAL_ERROR "${description} release manifest is missing: ${_manifest}")
	endif()

	lcc_read_release_manifest("${_manifest}")

	if(NOT LCC_RELEASE_MANIFEST_VERSION STREQUAL "1")
		message(FATAL_ERROR "${description} release manifest has unsupported version: ${LCC_RELEASE_MANIFEST_VERSION}")
	endif()
	if(NOT LCC_RELEASE_PACKAGE_NAME STREQUAL "licensecc")
		message(FATAL_ERROR "${description} release manifest has wrong package name: ${LCC_RELEASE_PACKAGE_NAME}")
	endif()
	if(NOT LCC_RELEASE_PACKAGE_PROFILE STREQUAL "${_expected_profile}")
		message(FATAL_ERROR "${description} release manifest has wrong package profile: ${LCC_RELEASE_PACKAGE_PROFILE}")
	endif()
	if(NOT LCC_RELEASE_LICENSE_FORMAT_MIN STREQUAL "200")
		message(FATAL_ERROR "${description} release manifest has wrong license format minimum: ${LCC_RELEASE_LICENSE_FORMAT_MIN}")
	endif()
	if(NOT LCC_RELEASE_LICENSE_FORMAT_MAX STREQUAL "201")
		message(FATAL_ERROR "${description} release manifest has wrong license format maximum: ${LCC_RELEASE_LICENSE_FORMAT_MAX}")
	endif()
	if(NOT LCC_RELEASE_PROJECT_NAME STREQUAL "${project_name}")
		message(FATAL_ERROR "${description} release manifest has wrong project: ${LCC_RELEASE_PROJECT_NAME}")
	endif()
	if(NOT LCC_RELEASE_PROJECT_MAGIC_NUM STREQUAL "${project_magic}")
		message(FATAL_ERROR "${description} release manifest has wrong project magic: ${LCC_RELEASE_PROJECT_MAGIC_NUM}")
	endif()
	if(NOT "${expected_config}" STREQUAL "" AND NOT LCC_RELEASE_BUILD_CONFIG STREQUAL "${expected_config}")
		message(FATAL_ERROR "${description} release manifest has wrong build config: ${LCC_RELEASE_BUILD_CONFIG}")
	endif()
	if("${LCC_RELEASE_PLATFORM}" STREQUAL "")
		message(FATAL_ERROR "${description} release manifest does not identify a platform")
	endif()

	foreach(_required_var IN ITEMS
		LCC_RELEASE_COMPILER_ID
		LCC_RELEASE_COMPILER_VERSION
		LCC_RELEASE_RUNTIME_LINKAGE
		LCC_RELEASE_ABI_TAG
		LCC_RELEASE_LICENSE_FORMAT_MIN
		LCC_RELEASE_LICENSE_FORMAT_MAX
		LCC_RELEASE_PUBLIC_KEY_PATH
		LCC_RELEASE_PUBLIC_KEY_SHA256
		LCC_RELEASE_PUBLIC_KEY_DER_SHA256
		LCC_RELEASE_PUBLIC_KEY_ID
		LCC_RELEASE_PUBLIC_KEY_DER_LEN
		LCC_RELEASE_PUBLIC_KEY_ALGORITHM
		LCC_RELEASE_PUBLIC_KEY_BITS
		LCC_RELEASE_SIGNATURE_ALGORITHM
		LCC_RELEASE_PROPERTIES_PATH
		LCC_RELEASE_PROPERTIES_SHA256)
		if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
			message(FATAL_ERROR "${description} release manifest is missing ${_required_var}")
		endif()
	endforeach()

	set(_public_key "${prefix}/${LCC_RELEASE_PUBLIC_KEY_PATH}")
	set(_properties "${prefix}/${LCC_RELEASE_PROPERTIES_PATH}")
	if(NOT EXISTS "${_public_key}")
		message(FATAL_ERROR "${description} manifest public key path is missing: ${_public_key}")
	endif()
	if(NOT EXISTS "${_properties}")
		message(FATAL_ERROR "${description} manifest properties path is missing: ${_properties}")
	endif()

	file(SHA256 "${_public_key}" _public_key_sha256)
	file(SHA256 "${_properties}" _properties_sha256)
	if(NOT _public_key_sha256 STREQUAL "${LCC_RELEASE_PUBLIC_KEY_SHA256}")
		message(FATAL_ERROR "${description} manifest public key SHA256 does not match ${_public_key}")
	endif()
	if(NOT _properties_sha256 STREQUAL "${LCC_RELEASE_PROPERTIES_SHA256}")
		message(FATAL_ERROR "${description} manifest properties SHA256 does not match ${_properties}")
	endif()
	if(NOT "${LCC_RELEASE_PUBLIC_KEY_DER_LEN}" MATCHES "^[0-9]+$")
		message(FATAL_ERROR "${description} manifest public key DER length is not numeric: ${LCC_RELEASE_PUBLIC_KEY_DER_LEN}")
	endif()
	if(NOT "${LCC_RELEASE_PUBLIC_KEY_DER_SHA256}" MATCHES "^[0-9a-f]+$")
		message(FATAL_ERROR "${description} manifest public key DER SHA256 is not lowercase hex: ${LCC_RELEASE_PUBLIC_KEY_DER_SHA256}")
	endif()
	string(LENGTH "${LCC_RELEASE_PUBLIC_KEY_DER_SHA256}" _public_key_der_sha256_len)
	if(NOT _public_key_der_sha256_len EQUAL 64)
		message(FATAL_ERROR "${description} manifest public key DER SHA256 has wrong length")
	endif()
	if(NOT "${LCC_RELEASE_PUBLIC_KEY_ID}" STREQUAL "sha256:${LCC_RELEASE_PUBLIC_KEY_DER_SHA256}")
		message(FATAL_ERROR "${description} manifest public key ID does not match DER SHA256")
	endif()
	if(NOT "${LCC_RELEASE_PUBLIC_KEY_ALGORITHM}" STREQUAL "rsa")
		message(FATAL_ERROR "${description} manifest public key algorithm is unsupported: ${LCC_RELEASE_PUBLIC_KEY_ALGORITHM}")
	endif()
	if(NOT "${LCC_RELEASE_PUBLIC_KEY_BITS}" MATCHES "^[0-9]+$")
		message(FATAL_ERROR "${description} manifest public key bit length is not numeric: ${LCC_RELEASE_PUBLIC_KEY_BITS}")
	endif()
	if(NOT "${LCC_RELEASE_SIGNATURE_ALGORITHM}" STREQUAL "rsa-pkcs1-sha256")
		message(FATAL_ERROR "${description} manifest signature algorithm is unsupported: ${LCC_RELEASE_SIGNATURE_ALGORITHM}")
	endif()
	_lcc_read_manifest_numeric_define(_license_format_min "${_properties}" LCC_SUPPORTED_LICENSE_FORMAT_MIN)
	_lcc_read_manifest_numeric_define(_license_format_max "${_properties}" LCC_SUPPORTED_LICENSE_FORMAT_MAX)
	if(NOT "${_license_format_min}" STREQUAL "${LCC_RELEASE_LICENSE_FORMAT_MIN}")
		message(FATAL_ERROR "${description} manifest license format minimum does not match ${_properties}")
	endif()
	if(NOT "${_license_format_max}" STREQUAL "${LCC_RELEASE_LICENSE_FORMAT_MAX}")
		message(FATAL_ERROR "${description} manifest license format maximum does not match ${_properties}")
	endif()
	_lcc_read_manifest_public_key_der_len(_public_key_der_len "${_public_key}")
	if("${_public_key_der_len}" STREQUAL "")
		message(FATAL_ERROR "${description} public key header is missing PUBLIC_KEY_LEN: ${_public_key}")
	endif()
	if(NOT "${_public_key_der_len}" STREQUAL "${LCC_RELEASE_PUBLIC_KEY_DER_LEN}")
		message(FATAL_ERROR "${description} manifest public key DER length does not match ${_public_key}")
	endif()
	_lcc_read_manifest_string_define(_public_key_der_sha256 "${_public_key}" LCC_PUBLIC_KEY_SHA256)
	if("${_public_key_der_sha256}" STREQUAL "")
		message(FATAL_ERROR "${description} public key header is missing LCC_PUBLIC_KEY_SHA256: ${_public_key}")
	endif()
	if(NOT "${_public_key_der_sha256}" STREQUAL "${LCC_RELEASE_PUBLIC_KEY_DER_SHA256}")
		message(FATAL_ERROR "${description} manifest public key DER SHA256 does not match ${_public_key}")
	endif()
	_lcc_read_manifest_string_define(_public_key_id "${_public_key}" LCC_PUBLIC_KEY_ID)
	if("${_public_key_id}" STREQUAL "")
		message(FATAL_ERROR "${description} public key header is missing LCC_PUBLIC_KEY_ID: ${_public_key}")
	endif()
	if(NOT "${_public_key_id}" STREQUAL "${LCC_RELEASE_PUBLIC_KEY_ID}")
		message(FATAL_ERROR "${description} manifest public key ID does not match ${_public_key}")
	endif()
	if(NOT "${_public_key_id}" STREQUAL "sha256:${_public_key_der_sha256}")
		message(FATAL_ERROR "${description} public key header ID does not match DER SHA256: ${_public_key}")
	endif()
	_lcc_read_manifest_string_define(_public_key_algorithm "${_public_key}" LCC_PUBLIC_KEY_ALGORITHM)
	if("${_public_key_algorithm}" STREQUAL "")
		message(FATAL_ERROR "${description} public key header is missing LCC_PUBLIC_KEY_ALGORITHM: ${_public_key}")
	endif()
	if(NOT "${_public_key_algorithm}" STREQUAL "${LCC_RELEASE_PUBLIC_KEY_ALGORITHM}")
		message(FATAL_ERROR "${description} manifest public key algorithm does not match ${_public_key}")
	endif()
	_lcc_read_manifest_numeric_define(_public_key_bits "${_public_key}" LCC_PUBLIC_KEY_BITS)
	if("${_public_key_bits}" STREQUAL "")
		message(FATAL_ERROR "${description} public key header is missing LCC_PUBLIC_KEY_BITS: ${_public_key}")
	endif()
	if(NOT "${_public_key_bits}" STREQUAL "${LCC_RELEASE_PUBLIC_KEY_BITS}")
		message(FATAL_ERROR "${description} manifest public key bit length does not match ${_public_key}")
	endif()
	_lcc_read_manifest_string_define(_signature_algorithm "${_public_key}" LCC_SIGNATURE_ALGORITHM)
	if("${_signature_algorithm}" STREQUAL "")
		message(FATAL_ERROR "${description} public key header is missing LCC_SIGNATURE_ALGORITHM: ${_public_key}")
	endif()
	if(NOT "${_signature_algorithm}" STREQUAL "${LCC_RELEASE_SIGNATURE_ALGORITHM}")
		message(FATAL_ERROR "${description} manifest signature algorithm does not match ${_public_key}")
	endif()
	if(LCC_RELEASE_PUBLIC_KEY_DER_LEN LESS 390)
		message(FATAL_ERROR "${description} manifest public key DER length is below the release minimum: ${LCC_RELEASE_PUBLIC_KEY_DER_LEN}")
	endif()
	if(LCC_RELEASE_PUBLIC_KEY_BITS LESS 3072)
		message(FATAL_ERROR "${description} manifest public key bit length is below the release minimum: ${LCC_RELEASE_PUBLIC_KEY_BITS}")
	endif()
endfunction()
