import type { LabeledPathFragment } from "../assemble.js";
import {
  ADMIN_AUTH_ERRORS,
  ADMIN_MUTATION_AUTH_ERRORS,
  ADMIN_SECURITY,
  csvExportResponse,
  deviceKeyIdParam,
  errorResponse,
  featureKeyParam,
  formatCsvParam,
  idempotencyKeyHeader,
  idParam,
  limitCursorParams,
  okResponse,
  SYNC_SECURITY,
} from "../components.js";

export const catalogPaths: LabeledPathFragment = {
  label: "catalog",
  entries: [
    ["/api/admin/catalog/features", {
    get: {
      tags: ["admin:plans"],
      summary: "List catalog feature definitions",
      operationId: "listCatalogFeatures",
      security: ADMIN_SECURITY,
      parameters: [
        { name: "project", in: "query", required: false, schema: { type: "string" } },
        { name: "status", in: "query", required: false, schema: { type: "string", enum: ["active", "disabled"] } },
        ...limitCursorParams(),
      ],
      responses: {
        "200": okResponse("Catalog feature page.", "#/components/schemas/CatalogFeaturesListData", "catalog_features_listed"),
        "400": errorResponse("Invalid filter or limit/cursor pagination bounds.", "invalid_request"),
        ...ADMIN_AUTH_ERRORS,
      },
    },
    post: {
      tags: ["admin:plans"],
      summary: "Create a catalog feature definition",
      operationId: "createCatalogFeature",
      security: ADMIN_SECURITY,
      parameters: [idempotencyKeyHeader],
      requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/CatalogFeatureInput" } } } },
      responses: {
        "200": okResponse("Catalog feature created.", "#/components/schemas/CatalogFeature", "catalog_feature_created"),
        "400": errorResponse("Invalid request / json / idempotency key.", "invalid_idempotency_key", "invalid_json", "invalid_request"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "409": errorResponse("Feature key already exists in the project.", "catalog_feature_conflict"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Catalog mutation failed.", "catalog_mutation_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
    ["/api/admin/catalog/features/{id}", {
    get: {
      tags: ["admin:plans"],
      summary: "Get a catalog feature definition",
      operationId: "getCatalogFeature",
      security: ADMIN_SECURITY,
      parameters: [idParam],
      responses: {
        "200": okResponse("Catalog feature.", "#/components/schemas/CatalogFeature", "catalog_feature"),
        ...ADMIN_AUTH_ERRORS,
        "404": errorResponse("No catalog feature with that id.", "catalog_feature_not_found"),
      },
    },
    patch: {
      tags: ["admin:plans"],
      summary: "Patch mutable catalog feature fields",
      operationId: "patchCatalogFeature",
      security: ADMIN_SECURITY,
      parameters: [idParam, idempotencyKeyHeader],
      requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/CatalogFeaturePatch" } } } },
      responses: {
        "200": okResponse("Catalog feature patched.", "#/components/schemas/CatalogFeature", "catalog_feature_patched"),
        "400": errorResponse("Invalid request / json / idempotency key.", "invalid_idempotency_key", "invalid_json", "invalid_request"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "404": errorResponse("No catalog feature with that id.", "catalog_feature_not_found"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Catalog mutation failed.", "catalog_mutation_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
    ["/api/admin/catalog/features/{id}/disable", {
    post: {
      tags: ["admin:plans"],
      summary: "Disable a catalog feature definition",
      operationId: "disableCatalogFeature",
      security: ADMIN_SECURITY,
      parameters: [idParam, idempotencyKeyHeader],
      requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ReasonRequiredBody" } } } },
      responses: {
        "200": okResponse("Catalog feature disabled.", "#/components/schemas/CatalogFeature", "catalog_feature_disabled"),
        "400": errorResponse("Invalid request / json / idempotency key, or missing reason.", "invalid_idempotency_key", "invalid_json", "invalid_request", "reason_required"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "404": errorResponse("No catalog feature with that id.", "catalog_feature_not_found"),
        "409": errorResponse("Feature is not in the expected prior status.", "catalog_status_conflict"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Catalog mutation failed.", "catalog_mutation_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
    ["/api/admin/catalog/features/{id}/reenable", {
    post: {
      tags: ["admin:plans"],
      summary: "Re-enable a catalog feature definition",
      operationId: "reenableCatalogFeature",
      security: ADMIN_SECURITY,
      parameters: [idParam, idempotencyKeyHeader],
      requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ReasonRequiredBody" } } } },
      responses: {
        "200": okResponse("Catalog feature re-enabled.", "#/components/schemas/CatalogFeature", "catalog_feature_reenabled"),
        "400": errorResponse("Invalid request / json / idempotency key.", "invalid_idempotency_key", "invalid_json", "invalid_request"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "404": errorResponse("No catalog feature with that id.", "catalog_feature_not_found"),
        "409": errorResponse("Feature is not in the expected prior status.", "catalog_status_conflict"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Catalog mutation failed.", "catalog_mutation_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
    ["/api/admin/catalog/plans", {
    get: {
      tags: ["admin:plans"],
      summary: "List catalog plans",
      operationId: "listCatalogPlans",
      security: ADMIN_SECURITY,
      parameters: [
        { name: "project", in: "query", required: false, schema: { type: "string" } },
        { name: "status", in: "query", required: false, schema: { type: "string", enum: ["active", "disabled"] } },
        ...limitCursorParams(),
      ],
      responses: {
        "200": okResponse("Catalog plan page.", "#/components/schemas/CatalogPlansListData", "catalog_plans_listed"),
        "400": errorResponse("Invalid filter or limit/cursor pagination bounds.", "invalid_request"),
        ...ADMIN_AUTH_ERRORS,
      },
    },
    post: {
      tags: ["admin:plans"],
      summary: "Create a catalog plan",
      operationId: "createCatalogPlan",
      security: ADMIN_SECURITY,
      parameters: [idempotencyKeyHeader],
      requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/CatalogPlanInput" } } } },
      responses: {
        "200": okResponse("Catalog plan created.", "#/components/schemas/CatalogPlan", "catalog_plan_created"),
        "400": errorResponse("Invalid request / json / idempotency key.", "invalid_idempotency_key", "invalid_json", "invalid_request"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "409": errorResponse("Plan key already exists in the project.", "catalog_plan_conflict"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Catalog mutation failed.", "catalog_mutation_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
    ["/api/admin/catalog/import", {
    post: {
      tags: ["admin:plans"],
      summary: "Preview or apply a portable catalog import manifest",
      operationId: "importCatalog",
      security: ADMIN_SECURITY,
      parameters: [
        idempotencyKeyHeader,
        { name: "dry_run", in: "query", required: false, schema: { type: "string", enum: ["1", "true"] } },
      ],
      requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/CatalogImportManifest" } } } },
      responses: {
        "200": okResponse("Catalog import previewed/applied.", "#/components/schemas/CatalogImportResult", "catalog_import_previewed", "catalog_import_applied"),
        "400": errorResponse("Invalid request / json / idempotency key.", "invalid_idempotency_key", "invalid_json", "invalid_request"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "404": errorResponse("Referenced feature or policy was not found.", "catalog_feature_not_found", "policy_not_found"),
        "409": errorResponse("Policy is disabled, from another project, or the import conflicts.", "policy_disabled", "invalid_plan_config", "catalog_import_conflict"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Catalog mutation failed.", "catalog_mutation_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
    ["/api/admin/catalog/plans/{id}", {
    get: {
      tags: ["admin:plans"],
      summary: "Get a catalog plan",
      operationId: "getCatalogPlan",
      security: ADMIN_SECURITY,
      parameters: [idParam],
      responses: {
        "200": okResponse("Catalog plan.", "#/components/schemas/CatalogPlan", "catalog_plan"),
        ...ADMIN_AUTH_ERRORS,
        "404": errorResponse("No catalog plan with that id.", "catalog_plan_not_found"),
      },
    },
    patch: {
      tags: ["admin:plans"],
      summary: "Patch mutable catalog plan fields",
      operationId: "patchCatalogPlan",
      security: ADMIN_SECURITY,
      parameters: [idParam, idempotencyKeyHeader],
      requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/CatalogPlanPatch" } } } },
      responses: {
        "200": okResponse("Catalog plan patched.", "#/components/schemas/CatalogPlan", "catalog_plan_patched"),
        "400": errorResponse("Invalid request / json / idempotency key.", "invalid_idempotency_key", "invalid_json", "invalid_request"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "404": errorResponse("No catalog plan with that id.", "catalog_plan_not_found"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Catalog mutation failed.", "catalog_mutation_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
    ["/api/admin/catalog/plans/{id}/disable", {
    post: {
      tags: ["admin:plans"],
      summary: "Disable a catalog plan",
      operationId: "disableCatalogPlan",
      security: ADMIN_SECURITY,
      parameters: [idParam, idempotencyKeyHeader],
      requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ReasonRequiredBody" } } } },
      responses: {
        "200": okResponse("Catalog plan disabled.", "#/components/schemas/CatalogPlan", "catalog_plan_disabled"),
        "400": errorResponse("Invalid request / json / idempotency key, or missing reason.", "invalid_idempotency_key", "invalid_json", "invalid_request", "reason_required"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "404": errorResponse("No catalog plan with that id.", "catalog_plan_not_found"),
        "409": errorResponse("Plan is not in the expected prior status.", "catalog_status_conflict"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Catalog mutation failed.", "catalog_mutation_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
    ["/api/admin/catalog/plans/{id}/reenable", {
    post: {
      tags: ["admin:plans"],
      summary: "Re-enable a catalog plan",
      operationId: "reenableCatalogPlan",
      security: ADMIN_SECURITY,
      parameters: [idParam, idempotencyKeyHeader],
      requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ReasonRequiredBody" } } } },
      responses: {
        "200": okResponse("Catalog plan re-enabled.", "#/components/schemas/CatalogPlan", "catalog_plan_reenabled"),
        "400": errorResponse("Invalid request / json / idempotency key.", "invalid_idempotency_key", "invalid_json", "invalid_request"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "404": errorResponse("No catalog plan with that id.", "catalog_plan_not_found"),

        "409": errorResponse("Plan is not in the expected prior status.", "catalog_status_conflict"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Catalog mutation failed.", "catalog_mutation_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
    ["/api/admin/catalog/plans/{id}/export", {
    get: {
      tags: ["admin:plans"],
      summary: "Export a catalog plan and its feature definitions as an import manifest",
      operationId: "exportCatalogPlan",
      security: ADMIN_SECURITY,
      parameters: [idParam],
      responses: {
        "200": okResponse("Catalog plan exported.", "#/components/schemas/CatalogImportManifest", "catalog_plan_exported"),
        ...ADMIN_AUTH_ERRORS,
        "404": errorResponse("No catalog plan with that id.", "catalog_plan_not_found"),
      },
    },
  }],
    ["/api/admin/catalog/plans/{id}/features", {
    get: {
      tags: ["admin:plans"],
      summary: "List feature rows configured on a catalog plan",
      operationId: "listCatalogPlanFeatures",
      security: ADMIN_SECURITY,
      parameters: [idParam, { name: "project", in: "query", required: false, schema: { type: "string" } }],
      responses: {
        "200": okResponse("Catalog plan feature rows.", "#/components/schemas/CatalogPlanFeaturesListData", "catalog_plan_features_listed"),
        ...ADMIN_AUTH_ERRORS,
      },
    },
    post: {
      tags: ["admin:plans"],
      summary: "Add or update a feature/add-on row on a catalog plan",
      operationId: "saveCatalogPlanFeature",
      security: ADMIN_SECURITY,
      parameters: [idParam, idempotencyKeyHeader],
      requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/CatalogPlanFeatureInput" } } } },
      responses: {
        "200": okResponse("Catalog plan feature saved.", "#/components/schemas/CatalogPlanFeature", "catalog_plan_feature_saved"),
        "400": errorResponse("Invalid request / json / idempotency key.", "invalid_idempotency_key", "invalid_json", "invalid_request"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "404": errorResponse("Referenced plan, feature, or policy was not found.", "catalog_plan_not_found", "catalog_feature_not_found", "policy_not_found"),
        "409": errorResponse("Invalid plan config, disabled policy, or add-on key conflict.", "invalid_plan_config", "policy_disabled", "catalog_plan_feature_conflict"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Catalog mutation failed.", "catalog_mutation_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
    ["/api/admin/catalog/plans/{id}/features/{featureKey}/disable", {
    post: {
      tags: ["admin:plans"],
      summary: "Disable a feature/add-on row on a catalog plan",
      operationId: "disableCatalogPlanFeature",
      security: ADMIN_SECURITY,
      parameters: [idParam, featureKeyParam, idempotencyKeyHeader],
      requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ReasonRequiredBody" } } } },
      responses: {
        "200": okResponse("Catalog plan feature disabled.", "#/components/schemas/CatalogPlanFeature", "catalog_plan_feature_disabled"),
        "400": errorResponse("Invalid request / json / idempotency key, or missing reason.", "invalid_idempotency_key", "invalid_json", "invalid_request", "reason_required"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "404": errorResponse("No feature row with that plan/feature key.", "catalog_plan_feature_not_found"),
        "409": errorResponse("Feature row is not in the expected prior status.", "catalog_status_conflict"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Catalog mutation failed.", "catalog_mutation_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
    ["/api/admin/catalog/plans/{id}/features/{featureKey}/reenable", {
    post: {
      tags: ["admin:plans"],
      summary: "Re-enable a feature/add-on row on a catalog plan",
      operationId: "reenableCatalogPlanFeature",
      security: ADMIN_SECURITY,
      parameters: [idParam, featureKeyParam, idempotencyKeyHeader],
      requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ReasonRequiredBody" } } } },
      responses: {
        "200": okResponse("Catalog plan feature re-enabled.", "#/components/schemas/CatalogPlanFeature", "catalog_plan_feature_reenabled"),
        "400": errorResponse("Invalid request / json / idempotency key.", "invalid_idempotency_key", "invalid_json", "invalid_request"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "404": errorResponse("No feature row with that plan/feature key.", "catalog_plan_feature_not_found"),
        "409": errorResponse("Feature row is not in the expected prior status.", "catalog_status_conflict"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Catalog mutation failed.", "catalog_mutation_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
    ["/api/admin/license-plans/preview", {
    post: {
      tags: ["admin:plans"],
      summary: "Persist a short-lived, server-bound preview of applying a catalog plan to a license",
      operationId: "previewLicensePlanProjection",
      security: ADMIN_SECURITY,
      requestBody: {
        required: true,
        content: { "application/json": { schema: { $ref: "#/components/schemas/PlanProjectionInput" } } },
      },
      responses: {
        "200": okResponse("Persisted projection diff with an opaque preview_id and one effective_at timestamp.", "#/components/schemas/PlanProjectionPreviewResponse", "license_plan_projection_previewed"),
        "400": errorResponse("Invalid request / json, or an unavailable add-on was requested.", "invalid_json", "invalid_request", "unknown_addon"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "404": errorResponse("Plan or referenced policy was not found.", "plan_not_found", "policy_not_found"),
        "409": errorResponse("Plan or referenced policy is disabled, the plan references a policy from another project, a different existing license fingerprint requires a deliberate transfer protocol, or `plan_projection_too_large` requires the operator to narrow the plan/add-on scope before previewing again. The nine-action bound keeps one Apply transaction below D1 Workers Free (50 query) and Paid (1,000 query) invocation limits.", "plan_disabled", "policy_disabled", "invalid_plan_config", "license_fingerprint_conflict", "plan_projection_too_large"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Projection failed, or dev bearer enabled outside development.", "plan_projection_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
    ["/api/admin/license-plans/apply", {
    post: {
      tags: ["admin:plans"],
      summary: "Atomically apply one unexpired server-bound catalog-plan preview",
      operationId: "applyLicensePlanProjection",
      security: ADMIN_SECURITY,
      parameters: [idempotencyKeyHeader],
      requestBody: {
        required: true,
        content: { "application/json": { schema: { $ref: "#/components/schemas/PlanProjectionApplyInput" } } },
      },
      responses: {
        "200": okResponse("Applied projection with created/updated/disabled entitlement records and assignment row.", "#/components/schemas/PlanProjectionApplyResult", "license_plan_projection_applied"),
        "400": errorResponse("Invalid request / json / idempotency key.", "invalid_idempotency_key", "invalid_json", "invalid_request"),
        ...ADMIN_MUTATION_AUTH_ERRORS,
        "409": errorResponse("Preview expired, was consumed, belongs to a different actor, its source generation changed, its derived grant has expired, or an assignment now has a different license fingerprint; re-preview before Apply. A fingerprint transfer needs a separate deliberate protocol.", "stale_projection_preview", "projection_preview_grant_expired", "license_fingerprint_conflict", "plan_projection_blocked"),
        "413": errorResponse("Request body exceeds 8192 bytes.", "body_too_large"),
        "500": errorResponse("Projection failed, mutation failed, or dev bearer enabled outside development.", "plan_projection_failed", "mutation_failed", "dev_bearer_forbidden_in_environment"),
      },
    },
  }],
  ],
};
