#!/usr/bin/env python3
import re
import sqlite3
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MIGRATIONS = ROOT / "migrations"
SNAPSHOT = ROOT / "schema.sql"

GENERATED_HEADER = (
    "-- GENERATED from migrations/ — edit migrations and run npm run schema:write\n"
    "-- Do not edit this file by hand; it is a canonicalized dump of the applied migrations.\n"
)

# Tables must be created before the indexes/triggers/views that reference them.
TYPE_ORDER = {"table": 0, "view": 1, "index": 2, "trigger": 3}


def normalize_sql(sql: str) -> str:
    sql = sql.replace('"', "")
    sql = re.sub(r"\bIF\s+NOT\s+EXISTS\s+", "", sql, flags=re.IGNORECASE)
    sql = re.sub(r"\s+", " ", sql.strip())
    return sql.lower()


def apply_sql(conn: sqlite3.Connection, path: Path) -> None:
    conn.executescript(path.read_text(encoding="utf-8"))


def build_from_migrations() -> sqlite3.Connection:
    conn = sqlite3.connect(":memory:")
    for path in sorted(MIGRATIONS.glob("*.sql")):
        apply_sql(conn, path)
    return conn


def build_from_snapshot() -> sqlite3.Connection:
    conn = sqlite3.connect(":memory:")
    apply_sql(conn, SNAPSHOT)
    return conn


def schema_objects(conn: sqlite3.Connection) -> dict[str, str]:
    rows = conn.execute(
        """
        SELECT type, name, tbl_name, sql
        FROM sqlite_schema
        WHERE name NOT LIKE 'sqlite_%'
          AND sql IS NOT NULL
          AND type IN ('table', 'index', 'trigger', 'view')
        ORDER BY type, name
        """,
    ).fetchall()
    return {f"{row[0]}:{row[1]}:{row[2]}": normalize_sql(row[3]) for row in rows}


def _idempotent(statement: str) -> str:
    """Restore the IF NOT EXISTS idiom the migrations use: sqlite_schema stores DDL with the clause
    stripped, but the snapshot's consumers (tests, humans, direct loads) rely on idempotent DDL."""
    for kind in ("TABLE", "INDEX", "UNIQUE INDEX", "TRIGGER", "VIEW"):
        prefix = f"CREATE {kind} "
        if statement.startswith(prefix) and not statement.startswith(f"CREATE {kind} IF NOT EXISTS "):
            return f"CREATE {kind} IF NOT EXISTS " + statement[len(prefix):]
    return statement


def dump_schema(conn: sqlite3.Connection) -> str:
    """Return a deterministic, dependency-ordered DDL dump of the applied schema."""
    rows = conn.execute(
        """
        SELECT type, name, sql
        FROM sqlite_schema
        WHERE name NOT LIKE 'sqlite_%'
          AND sql IS NOT NULL
          AND type IN ('table', 'index', 'trigger', 'view')
        """,
    ).fetchall()
    ordered = sorted(rows, key=lambda row: (TYPE_ORDER.get(row[0], 99), row[1]))
    statements = [_idempotent(row[2].strip().rstrip(";")) + ";" for row in ordered]
    return GENERATED_HEADER + "\n" + "\n\n".join(statements) + "\n"


def write_snapshot() -> int:
    dump = dump_schema(build_from_migrations())
    SNAPSHOT.write_text(dump, encoding="utf-8", newline="\n")
    print(f"wrote {SNAPSHOT.relative_to(ROOT)} from {len(list(MIGRATIONS.glob('*.sql')))} migrations")
    return 0


def check() -> int:
    migration_schema = schema_objects(build_from_migrations())
    snapshot_schema = schema_objects(build_from_snapshot())
    if migration_schema == snapshot_schema:
        print("schema parity ok")
        return 0

    migration_keys = set(migration_schema)
    snapshot_keys = set(snapshot_schema)
    for key in sorted(migration_keys - snapshot_keys):
        print(f"only in migrations: {key}")
    for key in sorted(snapshot_keys - migration_keys):
        print(f"only in schema.sql: {key}")
    for key in sorted(migration_keys & snapshot_keys):
        if migration_schema[key] != snapshot_schema[key]:
            print(f"schema mismatch: {key}")
            print(f"  migrations: {migration_schema[key]}")
            print(f"  schema.sql: {snapshot_schema[key]}")
    print("\nschema.sql is generated — run `npm run schema:write` to regenerate it.")
    return 1


def main(argv: list[str]) -> int:
    if "--write" in argv:
        return write_snapshot()
    return check()


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
