include("${CMAKE_CURRENT_LIST_DIR}/ReadReleaseManifest.cmake")

if(NOT DEFINED LCC_RELEASE_MANIFEST_PATH OR "${LCC_RELEASE_MANIFEST_PATH}" STREQUAL "")
	if(NOT DEFINED LCC_RELEASE_MANIFEST_PREFIX OR "${LCC_RELEASE_MANIFEST_PREFIX}" STREQUAL "")
		message(FATAL_ERROR "LCC_RELEASE_MANIFEST_PREFIX or LCC_RELEASE_MANIFEST_PATH is required")
	endif()
	if(NOT DEFINED LCC_RELEASE_MANIFEST_PROJECT_NAME OR "${LCC_RELEASE_MANIFEST_PROJECT_NAME}" STREQUAL "")
		message(FATAL_ERROR "LCC_RELEASE_MANIFEST_PROJECT_NAME is required when LCC_RELEASE_MANIFEST_PATH is not set")
	endif()
	get_filename_component(LCC_RELEASE_MANIFEST_PREFIX "${LCC_RELEASE_MANIFEST_PREFIX}" ABSOLUTE)
	set(LCC_RELEASE_MANIFEST_PATH
		"${LCC_RELEASE_MANIFEST_PREFIX}/share/licensecc/${LCC_RELEASE_MANIFEST_PROJECT_NAME}/release-manifest.cmake")
endif()

get_filename_component(LCC_RELEASE_MANIFEST_PATH "${LCC_RELEASE_MANIFEST_PATH}" ABSOLUTE)
if(NOT EXISTS "${LCC_RELEASE_MANIFEST_PATH}")
	message(FATAL_ERROR "Release manifest is missing: ${LCC_RELEASE_MANIFEST_PATH}")
endif()

lcc_read_release_manifest("${LCC_RELEASE_MANIFEST_PATH}")

foreach(_required_var IN ITEMS
	LCC_RELEASE_MANIFEST_VERSION
	LCC_RELEASE_PACKAGE_NAME
	LCC_RELEASE_PACKAGE_VERSION
	LCC_RELEASE_PACKAGE_PROFILE
	LCC_RELEASE_LICENSE_FORMAT_MIN
	LCC_RELEASE_LICENSE_FORMAT_MAX
	LCC_RELEASE_PROJECT_NAME
	LCC_RELEASE_PROJECT_MAGIC_NUM
	LCC_RELEASE_COMPILER_ID
	LCC_RELEASE_COMPILER_VERSION
	LCC_RELEASE_RUNTIME_LINKAGE
	LCC_RELEASE_ABI_TAG
	LCC_RELEASE_PUBLIC_KEY_PATH
	LCC_RELEASE_PUBLIC_KEY_SHA256
	LCC_RELEASE_PUBLIC_KEY_DER_SHA256
	LCC_RELEASE_PUBLIC_KEY_ID
	LCC_RELEASE_PUBLIC_KEY_DER_LEN
	LCC_RELEASE_PUBLIC_KEY_ALGORITHM
	LCC_RELEASE_PUBLIC_KEY_BITS
	LCC_RELEASE_SIGNATURE_ALGORITHM
	LCC_RELEASE_PROPERTIES_PATH
	LCC_RELEASE_PROPERTIES_SHA256)
	if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
		message(FATAL_ERROR "Release manifest is missing ${_required_var}: ${LCC_RELEASE_MANIFEST_PATH}")
	endif()
endforeach()

function(_lcc_assert_summary_value_safe name value)
	string(TOLOWER "${value}" _value_lower)
	set(_lcc_private_key_suffix "PRIVATE KEY")
	set(_lcc_private_key_marker_regex "BEGIN (RSA |EC |DSA |OPENSSH |ENCRYPTED )?${_lcc_private_key_suffix}|BEGIN ${_lcc_private_key_suffix}")
	if(_value_lower MATCHES "private[_-]?key" OR
	   value MATCHES "${_lcc_private_key_marker_regex}")
		message(FATAL_ERROR "Refusing to print unsafe release manifest value ${name}")
	endif()
endfunction()

foreach(_safe_var IN ITEMS
	LCC_RELEASE_PACKAGE_NAME
	LCC_RELEASE_PACKAGE_VERSION
	LCC_RELEASE_PACKAGE_PROFILE
	LCC_RELEASE_LICENSE_FORMAT_MIN
	LCC_RELEASE_LICENSE_FORMAT_MAX
	LCC_RELEASE_PROJECT_NAME
	LCC_RELEASE_PROJECT_MAGIC_NUM
	LCC_RELEASE_BUILD_CONFIG
	LCC_RELEASE_PLATFORM
	LCC_RELEASE_SYSTEM_PROCESSOR
	LCC_RELEASE_GENERATOR
	LCC_RELEASE_COMPILER_ID
	LCC_RELEASE_COMPILER_VERSION
	LCC_RELEASE_COMPILER_ARCHITECTURE
	LCC_RELEASE_RUNTIME_LINKAGE
	LCC_RELEASE_ABI_TAG
	LCC_RELEASE_PUBLIC_KEY_PATH
	LCC_RELEASE_PUBLIC_KEY_SHA256
	LCC_RELEASE_PUBLIC_KEY_DER_SHA256
	LCC_RELEASE_PUBLIC_KEY_ID
	LCC_RELEASE_PUBLIC_KEY_DER_LEN
	LCC_RELEASE_PUBLIC_KEY_ALGORITHM
	LCC_RELEASE_PUBLIC_KEY_BITS
	LCC_RELEASE_SIGNATURE_ALGORITHM
	LCC_RELEASE_PROPERTIES_PATH
	LCC_RELEASE_PROPERTIES_SHA256)
	_lcc_assert_summary_value_safe("${_safe_var}" "${${_safe_var}}")
endforeach()

message(STATUS "licensecc release manifest summary")
message(STATUS "  package: ${LCC_RELEASE_PACKAGE_NAME} ${LCC_RELEASE_PACKAGE_VERSION}")
message(STATUS "  profile: ${LCC_RELEASE_PACKAGE_PROFILE}")
message(STATUS "  license_format_min: ${LCC_RELEASE_LICENSE_FORMAT_MIN}")
message(STATUS "  license_format_max: ${LCC_RELEASE_LICENSE_FORMAT_MAX}")
message(STATUS "  project: ${LCC_RELEASE_PROJECT_NAME}")
message(STATUS "  project_magic: ${LCC_RELEASE_PROJECT_MAGIC_NUM}")
message(STATUS "  build_config: ${LCC_RELEASE_BUILD_CONFIG}")
message(STATUS "  platform: ${LCC_RELEASE_PLATFORM}")
message(STATUS "  processor: ${LCC_RELEASE_SYSTEM_PROCESSOR}")
message(STATUS "  generator: ${LCC_RELEASE_GENERATOR}")
message(STATUS "  compiler: ${LCC_RELEASE_COMPILER_ID} ${LCC_RELEASE_COMPILER_VERSION}")
message(STATUS "  compiler_architecture: ${LCC_RELEASE_COMPILER_ARCHITECTURE}")
message(STATUS "  runtime_linkage: ${LCC_RELEASE_RUNTIME_LINKAGE}")
message(STATUS "  abi_tag: ${LCC_RELEASE_ABI_TAG}")
message(STATUS "  public_key_path: ${LCC_RELEASE_PUBLIC_KEY_PATH}")
message(STATUS "  public_key_sha256: ${LCC_RELEASE_PUBLIC_KEY_SHA256}")
message(STATUS "  public_key_der_sha256: ${LCC_RELEASE_PUBLIC_KEY_DER_SHA256}")
message(STATUS "  public_key_id: ${LCC_RELEASE_PUBLIC_KEY_ID}")
message(STATUS "  public_key_der_len: ${LCC_RELEASE_PUBLIC_KEY_DER_LEN}")
message(STATUS "  public_key_algorithm: ${LCC_RELEASE_PUBLIC_KEY_ALGORITHM}")
message(STATUS "  public_key_bits: ${LCC_RELEASE_PUBLIC_KEY_BITS}")
message(STATUS "  signature_algorithm: ${LCC_RELEASE_SIGNATURE_ALGORITHM}")
message(STATUS "  properties_path: ${LCC_RELEASE_PROPERTIES_PATH}")
message(STATUS "  properties_sha256: ${LCC_RELEASE_PROPERTIES_SHA256}")
