include("${CMAKE_CURRENT_LIST_DIR}/ValidateLicenseccIdentity.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ReadReleaseManifest.cmake")

if(NOT DEFINED LCC_ARTIFACT_SCAN_ROOT OR "${LCC_ARTIFACT_SCAN_ROOT}" STREQUAL "")
	set(LCC_ARTIFACT_SCAN_ROOT "${CMAKE_INSTALL_PREFIX}")
endif()

if(NOT DEFINED LCC_ARTIFACT_ALLOW_TOOLS)
	set(LCC_ARTIFACT_ALLOW_TOOLS OFF)
endif()
if(NOT DEFINED LCC_ARTIFACT_EXPECTED_PROFILE)
	set(LCC_ARTIFACT_EXPECTED_PROFILE "")
endif()
if(NOT DEFINED LCC_ARTIFACT_EXPECTED_PROJECT_NAME)
	set(LCC_ARTIFACT_EXPECTED_PROJECT_NAME "")
endif()
if(NOT DEFINED LCC_MIN_RELEASE_PUBLIC_KEY_DER_LEN OR "${LCC_MIN_RELEASE_PUBLIC_KEY_DER_LEN}" STREQUAL "")
	set(LCC_MIN_RELEASE_PUBLIC_KEY_DER_LEN 390)
endif()
if(NOT "${LCC_MIN_RELEASE_PUBLIC_KEY_DER_LEN}" MATCHES "^[0-9]+$")
	message(FATAL_ERROR "LCC_MIN_RELEASE_PUBLIC_KEY_DER_LEN must be numeric: ${LCC_MIN_RELEASE_PUBLIC_KEY_DER_LEN}")
endif()
if(NOT DEFINED LCC_MIN_RELEASE_PUBLIC_KEY_BITS OR "${LCC_MIN_RELEASE_PUBLIC_KEY_BITS}" STREQUAL "")
	set(LCC_MIN_RELEASE_PUBLIC_KEY_BITS 3072)
endif()
if(NOT "${LCC_MIN_RELEASE_PUBLIC_KEY_BITS}" MATCHES "^[0-9]+$")
	message(FATAL_ERROR "LCC_MIN_RELEASE_PUBLIC_KEY_BITS must be numeric: ${LCC_MIN_RELEASE_PUBLIC_KEY_BITS}")
endif()

get_filename_component(LCC_ARTIFACT_SCAN_ROOT "${LCC_ARTIFACT_SCAN_ROOT}" ABSOLUTE)
if(NOT EXISTS "${LCC_ARTIFACT_SCAN_ROOT}")
	message(FATAL_ERROR "Artifact scan root does not exist: ${LCC_ARTIFACT_SCAN_ROOT}")
endif()

file(GLOB_RECURSE _lcc_artifact_files LIST_DIRECTORIES false "${LCC_ARTIFACT_SCAN_ROOT}/*")
set(_lcc_artifact_violations)
set(_lcc_release_manifests)

set(_lcc_enforce_runtime_allowlist OFF)
string(TOLOWER "${LCC_ARTIFACT_EXPECTED_PROFILE}" _lcc_expected_profile_lower)
if(NOT "${LCC_ARTIFACT_EXPECTED_PROFILE}" STREQUAL "")
	lcc_validate_package_profile("${LCC_ARTIFACT_EXPECTED_PROFILE}")
endif()
if(_lcc_expected_profile_lower STREQUAL "runtime")
	if("${LCC_ARTIFACT_EXPECTED_PROJECT_NAME}" STREQUAL "")
		message(FATAL_ERROR "LCC_ARTIFACT_EXPECTED_PROJECT_NAME is required for runtime profile scanning")
	endif()
	lcc_validate_project_name("${LCC_ARTIFACT_EXPECTED_PROJECT_NAME}")
	set(_lcc_enforce_runtime_allowlist ON)
	string(TOLOWER "${LCC_ARTIFACT_EXPECTED_PROJECT_NAME}" _lcc_expected_project_lower)
	string(REGEX REPLACE "([][+.*()^$?|\\\\-])" "\\\\\\1" _lcc_expected_project_re "${_lcc_expected_project_lower}")
endif()

function(_lcc_runtime_path_allowed rel_path_lower out_var)
	set(_allowed OFF)
	if(rel_path_lower STREQUAL "include/licensecc/datatypes.h" OR
	   rel_path_lower STREQUAL "include/licensecc/licensecc.h" OR
	   rel_path_lower STREQUAL "lib/cmake/licensecc/licensecc-config.cmake" OR
	   rel_path_lower STREQUAL "lib/cmake/licensecc/readreleasemanifest.cmake" OR
	   rel_path_lower STREQUAL "lib/cmake/licensecc/licensecc-config-version.cmake")
		set(_allowed ON)
	elseif(rel_path_lower MATCHES "^include/licensecc/${_lcc_expected_project_re}/(licensecc_properties\\.h|public_key\\.h)$")
		set(_allowed ON)
	elseif(rel_path_lower MATCHES "^lib/licensecc/${_lcc_expected_project_re}/(licensecc_static\\.lib|liblicensecc_static\\.a)$")
		set(_allowed ON)
	elseif(rel_path_lower MATCHES "^lib/licensecc/${_lcc_expected_project_re}/cmake/licensecc(-[a-z0-9_]+)?\\.cmake$")
		set(_allowed ON)
	elseif(rel_path_lower MATCHES "^share/licensecc/${_lcc_expected_project_re}/release-manifest\\.cmake$")
		set(_allowed ON)
	endif()
	set(${out_var} "${_allowed}" PARENT_SCOPE)
endfunction()

function(_lcc_resolve_manifest_path out_abs out_ok rel_path)
	set(${out_abs} "" PARENT_SCOPE)
	set(${out_ok} OFF PARENT_SCOPE)
	if("${rel_path}" STREQUAL "")
		return()
	endif()
	if(IS_ABSOLUTE "${rel_path}")
		return()
	endif()
	file(TO_CMAKE_PATH "${rel_path}" _rel_path_cmake)
	if(_rel_path_cmake MATCHES "(^|/)\\.\\.(/|$)")
		return()
	endif()
	get_filename_component(_abs "${LCC_ARTIFACT_SCAN_ROOT}/${_rel_path_cmake}" ABSOLUTE)
	file(TO_CMAKE_PATH "${_abs}" _abs_cmake)
	file(TO_CMAKE_PATH "${LCC_ARTIFACT_SCAN_ROOT}" _root_cmake)
	string(FIND "${_abs_cmake}/" "${_root_cmake}/" _under_root)
	if(NOT _under_root EQUAL 0)
		return()
	endif()
	set(${out_abs} "${_abs}" PARENT_SCOPE)
	set(${out_ok} ON PARENT_SCOPE)
endfunction()

function(_lcc_read_public_key_numeric_define out_var public_key_header define_name)
	set(${out_var} "" PARENT_SCOPE)
	file(STRINGS "${public_key_header}" _lcc_public_key_numeric_lines
		REGEX "^[ \t]*#define[ \t]+${define_name}[ \t]+[^ \t]+[ \t]*$"
		LIMIT_COUNT 1)
	if(NOT _lcc_public_key_numeric_lines)
		return()
	endif()
	list(GET _lcc_public_key_numeric_lines 0 _lcc_public_key_numeric_line)
	string(REGEX REPLACE "^[ \t]*#define[ \t]+${define_name}[ \t]+([^ \t]+)[ \t]*$" "\\1"
		_lcc_public_key_numeric_value "${_lcc_public_key_numeric_line}")
	set(${out_var} "${_lcc_public_key_numeric_value}" PARENT_SCOPE)
endfunction()

function(_lcc_read_public_key_string_define out_var public_key_header define_name)
	set(${out_var} "" PARENT_SCOPE)
	file(STRINGS "${public_key_header}" _lcc_public_key_string_lines
		REGEX "^[ \t]*#define[ \t]+${define_name}[ \t]+\"[^\"]*\"[ \t]*$"
		LIMIT_COUNT 1)
	if(NOT _lcc_public_key_string_lines)
		return()
	endif()
	list(GET _lcc_public_key_string_lines 0 _lcc_public_key_string_line)
	string(REGEX REPLACE "^[ \t]*#define[ \t]+${define_name}[ \t]+\"([^\"]*)\"[ \t]*$" "\\1"
		_lcc_public_key_string_value "${_lcc_public_key_string_line}")
	set(${out_var} "${_lcc_public_key_string_value}" PARENT_SCOPE)
endfunction()

function(_lcc_read_public_key_der_len out_var public_key_header)
	_lcc_read_public_key_numeric_define(_lcc_public_key_len "${public_key_header}" PUBLIC_KEY_LEN)
	set(${out_var} "${_lcc_public_key_len}" PARENT_SCOPE)
endfunction()

foreach(_file IN LISTS _lcc_artifact_files)
	file(TO_CMAKE_PATH "${_file}" _file_cmake)
	file(RELATIVE_PATH _rel_file "${LCC_ARTIFACT_SCAN_ROOT}" "${_file}")
	file(TO_CMAKE_PATH "${_rel_file}" _rel_file_cmake)
	get_filename_component(_name "${_file}" NAME)
	string(TOLOWER "${_name}" _name_lower)
	string(TOLOWER "${_rel_file_cmake}" _path_lower)

	if(_path_lower MATCHES "^share/licensecc/[^/]+/release-manifest\\.cmake$")
		list(APPEND _lcc_release_manifests "${_file}")
	endif()

	if(_lcc_enforce_runtime_allowlist)
		_lcc_runtime_path_allowed("${_path_lower}" _lcc_path_allowed)
		if(NOT _lcc_path_allowed)
			list(APPEND _lcc_artifact_violations "unexpected runtime artifact path: ${_rel_file_cmake}")
		endif()
	endif()

	if(_name_lower STREQUAL "private_key.rsa" OR _name_lower MATCHES ".*\\.(pem|key|p12|pfx)$")
		list(APPEND _lcc_artifact_violations "forbidden key-like file: ${_file}")
	endif()
	if(_path_lower MATCHES "(^|/)projects/")
		list(APPEND _lcc_artifact_violations "generated project folder present: ${_file}")
	endif()

	if(NOT LCC_ARTIFACT_ALLOW_TOOLS)
		if(_name_lower MATCHES "^lccgen(\\.exe)?$" OR _name_lower MATCHES "^lccinspector(\\.exe)?$")
			list(APPEND _lcc_artifact_violations "tooling executable present in runtime artifact: ${_file}")
		endif()
		if(_path_lower MATCHES "/cmake/lccgen/" OR _path_lower MATCHES "/lib/cmake/lccgen/")
			list(APPEND _lcc_artifact_violations "lccgen package config present in runtime artifact: ${_file}")
		endif()
	endif()

	set(_lcc_skip_content_marker_scan OFF)
	if(LCC_ARTIFACT_ALLOW_TOOLS AND (_name_lower MATCHES "^lccgen(\\.exe)?$" OR _name_lower MATCHES "^lccinspector(\\.exe)?$"))
		set(_lcc_skip_content_marker_scan ON)
	endif()
	if(NOT _lcc_skip_content_marker_scan)
		set(_lcc_private_key_suffix "PRIVATE KEY")
		set(_lcc_private_key_marker_regex "BEGIN (RSA |EC |DSA |OPENSSH |ENCRYPTED )?${_lcc_private_key_suffix}|BEGIN ${_lcc_private_key_suffix}")
		file(STRINGS "${_file}" _private_key_markers
			REGEX "${_lcc_private_key_marker_regex}"
			LIMIT_COUNT 1)
		if(_private_key_markers)
			list(APPEND _lcc_artifact_violations "private-key marker present in file content: ${_file}")
		endif()
	endif()
endforeach()

if(_lcc_enforce_runtime_allowlist)
	list(LENGTH _lcc_release_manifests _lcc_manifest_count)
	if(NOT _lcc_manifest_count EQUAL 1)
		list(APPEND _lcc_artifact_violations
			"runtime artifact must contain exactly one release manifest for ${LCC_ARTIFACT_EXPECTED_PROJECT_NAME}; found ${_lcc_manifest_count}: ${_lcc_release_manifests}")
	else()
		list(GET _lcc_release_manifests 0 _lcc_manifest)
		lcc_read_release_manifest("${_lcc_manifest}")

		foreach(_required_var IN ITEMS
			LCC_RELEASE_MANIFEST_VERSION
			LCC_RELEASE_PACKAGE_NAME
			LCC_RELEASE_PACKAGE_VERSION
			LCC_RELEASE_PACKAGE_PROFILE
			LCC_RELEASE_LICENSE_FORMAT_MIN
			LCC_RELEASE_LICENSE_FORMAT_MAX
			LCC_RELEASE_PROJECT_NAME
			LCC_RELEASE_PROJECT_MAGIC_NUM
			LCC_RELEASE_BUILD_CONFIG
			LCC_RELEASE_PLATFORM
			LCC_RELEASE_COMPILER_ID
			LCC_RELEASE_COMPILER_VERSION
			LCC_RELEASE_RUNTIME_LINKAGE
			LCC_RELEASE_ABI_TAG
			LCC_RELEASE_PUBLIC_KEY_PATH
			LCC_RELEASE_PUBLIC_KEY_SHA256
			LCC_RELEASE_PUBLIC_KEY_DER_SHA256
			LCC_RELEASE_PUBLIC_KEY_ID
			LCC_RELEASE_PUBLIC_KEY_DER_LEN
			LCC_RELEASE_PUBLIC_KEY_ALGORITHM
			LCC_RELEASE_PUBLIC_KEY_BITS
			LCC_RELEASE_SIGNATURE_ALGORITHM
			LCC_RELEASE_PROPERTIES_PATH
			LCC_RELEASE_PROPERTIES_SHA256)
			if(NOT DEFINED ${_required_var} OR "${${_required_var}}" STREQUAL "")
				list(APPEND _lcc_artifact_violations "release manifest is missing ${_required_var}: ${_lcc_manifest}")
			endif()
		endforeach()

		if(DEFINED LCC_RELEASE_MANIFEST_VERSION AND NOT LCC_RELEASE_MANIFEST_VERSION STREQUAL "1")
			list(APPEND _lcc_artifact_violations "release manifest has unsupported version: ${LCC_RELEASE_MANIFEST_VERSION}")
		endif()
		if(DEFINED LCC_RELEASE_PACKAGE_NAME AND NOT LCC_RELEASE_PACKAGE_NAME STREQUAL "licensecc")
			list(APPEND _lcc_artifact_violations "release manifest has wrong package name: ${LCC_RELEASE_PACKAGE_NAME}")
		endif()
		if(DEFINED LCC_RELEASE_PACKAGE_PROFILE AND NOT LCC_RELEASE_PACKAGE_PROFILE STREQUAL "${LCC_ARTIFACT_EXPECTED_PROFILE}")
			list(APPEND _lcc_artifact_violations "release manifest has wrong package profile: ${LCC_RELEASE_PACKAGE_PROFILE}")
		endif()
		if(DEFINED LCC_RELEASE_PROJECT_NAME AND NOT LCC_RELEASE_PROJECT_NAME STREQUAL "${LCC_ARTIFACT_EXPECTED_PROJECT_NAME}")
			list(APPEND _lcc_artifact_violations "release manifest has wrong project: ${LCC_RELEASE_PROJECT_NAME}")
		endif()
		if(DEFINED LCC_RELEASE_LICENSE_FORMAT_MIN AND
		   NOT "${LCC_RELEASE_LICENSE_FORMAT_MIN}" MATCHES "^[0-9]+$")
			list(APPEND _lcc_artifact_violations "release manifest license format minimum is not numeric: ${LCC_RELEASE_LICENSE_FORMAT_MIN}")
		endif()
		if(DEFINED LCC_RELEASE_LICENSE_FORMAT_MAX AND
		   NOT "${LCC_RELEASE_LICENSE_FORMAT_MAX}" MATCHES "^[0-9]+$")
			list(APPEND _lcc_artifact_violations "release manifest license format maximum is not numeric: ${LCC_RELEASE_LICENSE_FORMAT_MAX}")
		endif()
		if(DEFINED LCC_RELEASE_LICENSE_FORMAT_MIN AND
		   DEFINED LCC_RELEASE_LICENSE_FORMAT_MAX AND
		   "${LCC_RELEASE_LICENSE_FORMAT_MIN}" MATCHES "^[0-9]+$" AND
		   "${LCC_RELEASE_LICENSE_FORMAT_MAX}" MATCHES "^[0-9]+$" AND
		   LCC_RELEASE_LICENSE_FORMAT_MIN GREATER LCC_RELEASE_LICENSE_FORMAT_MAX)
			list(APPEND _lcc_artifact_violations "release manifest license format minimum exceeds maximum: ${LCC_RELEASE_LICENSE_FORMAT_MIN} > ${LCC_RELEASE_LICENSE_FORMAT_MAX}")
		endif()
		if(DEFINED LCC_RELEASE_PUBLIC_KEY_DER_LEN AND
		   NOT "${LCC_RELEASE_PUBLIC_KEY_DER_LEN}" MATCHES "^[0-9]+$")
			list(APPEND _lcc_artifact_violations "release manifest public key DER length is not numeric: ${LCC_RELEASE_PUBLIC_KEY_DER_LEN}")
		endif()
		if(DEFINED LCC_RELEASE_PUBLIC_KEY_BITS AND
		   NOT "${LCC_RELEASE_PUBLIC_KEY_BITS}" MATCHES "^[0-9]+$")
			list(APPEND _lcc_artifact_violations "release manifest public key bit length is not numeric: ${LCC_RELEASE_PUBLIC_KEY_BITS}")
		endif()
		if(DEFINED LCC_RELEASE_PUBLIC_KEY_DER_SHA256)
			if(NOT "${LCC_RELEASE_PUBLIC_KEY_DER_SHA256}" MATCHES "^[0-9a-f]+$")
				list(APPEND _lcc_artifact_violations "release manifest public key DER SHA256 is not lowercase hex: ${LCC_RELEASE_PUBLIC_KEY_DER_SHA256}")
			endif()
			string(LENGTH "${LCC_RELEASE_PUBLIC_KEY_DER_SHA256}" _lcc_manifest_public_key_der_sha256_len)
			if(NOT _lcc_manifest_public_key_der_sha256_len EQUAL 64)
				list(APPEND _lcc_artifact_violations "release manifest public key DER SHA256 has wrong length")
			endif()
		endif()
		if(DEFINED LCC_RELEASE_PUBLIC_KEY_ID AND
		   DEFINED LCC_RELEASE_PUBLIC_KEY_DER_SHA256 AND
		   NOT "${LCC_RELEASE_PUBLIC_KEY_ID}" STREQUAL "sha256:${LCC_RELEASE_PUBLIC_KEY_DER_SHA256}")
			list(APPEND _lcc_artifact_violations "release manifest public key ID does not match DER SHA256")
		endif()
		if(DEFINED LCC_RELEASE_PUBLIC_KEY_ALGORITHM AND
		   NOT "${LCC_RELEASE_PUBLIC_KEY_ALGORITHM}" STREQUAL "rsa")
			list(APPEND _lcc_artifact_violations "release manifest public key algorithm is unsupported: ${LCC_RELEASE_PUBLIC_KEY_ALGORITHM}")
		endif()
		if(DEFINED LCC_RELEASE_SIGNATURE_ALGORITHM AND
		   NOT "${LCC_RELEASE_SIGNATURE_ALGORITHM}" STREQUAL "rsa-pkcs1-sha256")
			list(APPEND _lcc_artifact_violations "release manifest signature algorithm is unsupported: ${LCC_RELEASE_SIGNATURE_ALGORITHM}")
		endif()

		set(_lcc_expected_public_key_path "include/licensecc/${LCC_ARTIFACT_EXPECTED_PROJECT_NAME}/public_key.h")
		set(_lcc_expected_properties_path "include/licensecc/${LCC_ARTIFACT_EXPECTED_PROJECT_NAME}/licensecc_properties.h")
		if(DEFINED LCC_RELEASE_PUBLIC_KEY_PATH AND NOT LCC_RELEASE_PUBLIC_KEY_PATH STREQUAL "${_lcc_expected_public_key_path}")
			list(APPEND _lcc_artifact_violations "release manifest has wrong public key path: ${LCC_RELEASE_PUBLIC_KEY_PATH}")
		endif()
		if(DEFINED LCC_RELEASE_PROPERTIES_PATH AND NOT LCC_RELEASE_PROPERTIES_PATH STREQUAL "${_lcc_expected_properties_path}")
			list(APPEND _lcc_artifact_violations "release manifest has wrong properties path: ${LCC_RELEASE_PROPERTIES_PATH}")
		endif()

		if(DEFINED LCC_RELEASE_PUBLIC_KEY_PATH)
			_lcc_resolve_manifest_path(_lcc_public_key_abs _lcc_public_key_path_ok "${LCC_RELEASE_PUBLIC_KEY_PATH}")
			if(NOT _lcc_public_key_path_ok)
				list(APPEND _lcc_artifact_violations "release manifest public key path is unsafe: ${LCC_RELEASE_PUBLIC_KEY_PATH}")
			elseif(NOT EXISTS "${_lcc_public_key_abs}")
				list(APPEND _lcc_artifact_violations "release manifest public key path is missing: ${LCC_RELEASE_PUBLIC_KEY_PATH}")
			elseif(DEFINED LCC_RELEASE_PUBLIC_KEY_SHA256)
				file(SHA256 "${_lcc_public_key_abs}" _lcc_public_key_sha256)
				if(NOT _lcc_public_key_sha256 STREQUAL "${LCC_RELEASE_PUBLIC_KEY_SHA256}")
					list(APPEND _lcc_artifact_violations "release manifest public key SHA256 does not match ${LCC_RELEASE_PUBLIC_KEY_PATH}")
				endif()
			endif()
			if(EXISTS "${_lcc_public_key_abs}")
				_lcc_read_public_key_der_len(_lcc_public_key_der_len "${_lcc_public_key_abs}")
				_lcc_read_public_key_string_define(_lcc_public_key_algorithm "${_lcc_public_key_abs}" LCC_PUBLIC_KEY_ALGORITHM)
				_lcc_read_public_key_numeric_define(_lcc_public_key_bits "${_lcc_public_key_abs}" LCC_PUBLIC_KEY_BITS)
				_lcc_read_public_key_string_define(_lcc_public_key_der_sha256 "${_lcc_public_key_abs}" LCC_PUBLIC_KEY_SHA256)
				_lcc_read_public_key_string_define(_lcc_public_key_id "${_lcc_public_key_abs}" LCC_PUBLIC_KEY_ID)
				_lcc_read_public_key_string_define(_lcc_signature_algorithm "${_lcc_public_key_abs}" LCC_SIGNATURE_ALGORITHM)
				if("${_lcc_public_key_der_len}" STREQUAL "")
					list(APPEND _lcc_artifact_violations "release manifest public key length is missing from ${LCC_RELEASE_PUBLIC_KEY_PATH}")
				elseif(NOT "${_lcc_public_key_der_len}" MATCHES "^[0-9]+$")
					list(APPEND _lcc_artifact_violations "release manifest public key length is not numeric in ${LCC_RELEASE_PUBLIC_KEY_PATH}: ${_lcc_public_key_der_len}")
				else()
					if(DEFINED LCC_RELEASE_PUBLIC_KEY_DER_LEN AND
					   NOT "${_lcc_public_key_der_len}" STREQUAL "${LCC_RELEASE_PUBLIC_KEY_DER_LEN}")
						list(APPEND _lcc_artifact_violations "release manifest public key DER length does not match ${LCC_RELEASE_PUBLIC_KEY_PATH}")
					endif()
					if(_lcc_public_key_der_len LESS LCC_MIN_RELEASE_PUBLIC_KEY_DER_LEN)
						list(APPEND _lcc_artifact_violations "release public key length is below minimum: ${_lcc_public_key_der_len} < ${LCC_MIN_RELEASE_PUBLIC_KEY_DER_LEN}")
					endif()
				endif()
				if("${_lcc_public_key_algorithm}" STREQUAL "")
					list(APPEND _lcc_artifact_violations "release manifest public key algorithm is missing from ${LCC_RELEASE_PUBLIC_KEY_PATH}")
				else()
					if(DEFINED LCC_RELEASE_PUBLIC_KEY_ALGORITHM AND
					   NOT "${_lcc_public_key_algorithm}" STREQUAL "${LCC_RELEASE_PUBLIC_KEY_ALGORITHM}")
						list(APPEND _lcc_artifact_violations "release manifest public key algorithm does not match ${LCC_RELEASE_PUBLIC_KEY_PATH}")
					endif()
					if(NOT "${_lcc_public_key_algorithm}" STREQUAL "rsa")
						list(APPEND _lcc_artifact_violations "release public key algorithm is unsupported: ${_lcc_public_key_algorithm}")
					endif()
				endif()
				if("${_lcc_public_key_bits}" STREQUAL "")
					list(APPEND _lcc_artifact_violations "release manifest public key bit length is missing from ${LCC_RELEASE_PUBLIC_KEY_PATH}")
				elseif(NOT "${_lcc_public_key_bits}" MATCHES "^[0-9]+$")
					list(APPEND _lcc_artifact_violations "release manifest public key bit length is not numeric in ${LCC_RELEASE_PUBLIC_KEY_PATH}: ${_lcc_public_key_bits}")
				else()
					if(DEFINED LCC_RELEASE_PUBLIC_KEY_BITS AND
					   NOT "${_lcc_public_key_bits}" STREQUAL "${LCC_RELEASE_PUBLIC_KEY_BITS}")
						list(APPEND _lcc_artifact_violations "release manifest public key bit length does not match ${LCC_RELEASE_PUBLIC_KEY_PATH}")
					endif()
					if(_lcc_public_key_bits LESS LCC_MIN_RELEASE_PUBLIC_KEY_BITS)
						list(APPEND _lcc_artifact_violations "release public key bit length is below minimum: ${_lcc_public_key_bits} < ${LCC_MIN_RELEASE_PUBLIC_KEY_BITS}")
					endif()
				endif()
				if("${_lcc_public_key_der_sha256}" STREQUAL "")
					list(APPEND _lcc_artifact_violations "release manifest public key DER SHA256 is missing from ${LCC_RELEASE_PUBLIC_KEY_PATH}")
				else()
					if(DEFINED LCC_RELEASE_PUBLIC_KEY_DER_SHA256 AND
					   NOT "${_lcc_public_key_der_sha256}" STREQUAL "${LCC_RELEASE_PUBLIC_KEY_DER_SHA256}")
						list(APPEND _lcc_artifact_violations "release manifest public key DER SHA256 does not match ${LCC_RELEASE_PUBLIC_KEY_PATH}")
					endif()
				endif()
				if("${_lcc_public_key_id}" STREQUAL "")
					list(APPEND _lcc_artifact_violations "release manifest public key ID is missing from ${LCC_RELEASE_PUBLIC_KEY_PATH}")
				else()
					if(DEFINED LCC_RELEASE_PUBLIC_KEY_ID AND
					   NOT "${_lcc_public_key_id}" STREQUAL "${LCC_RELEASE_PUBLIC_KEY_ID}")
						list(APPEND _lcc_artifact_violations "release manifest public key ID does not match ${LCC_RELEASE_PUBLIC_KEY_PATH}")
					endif()
					if(NOT "${_lcc_public_key_id}" STREQUAL "sha256:${_lcc_public_key_der_sha256}")
						list(APPEND _lcc_artifact_violations "release public key ID does not match DER SHA256")
					endif()
				endif()
				if("${_lcc_signature_algorithm}" STREQUAL "")
					list(APPEND _lcc_artifact_violations "release manifest signature algorithm is missing from ${LCC_RELEASE_PUBLIC_KEY_PATH}")
				else()
					if(DEFINED LCC_RELEASE_SIGNATURE_ALGORITHM AND
					   NOT "${_lcc_signature_algorithm}" STREQUAL "${LCC_RELEASE_SIGNATURE_ALGORITHM}")
						list(APPEND _lcc_artifact_violations "release manifest signature algorithm does not match ${LCC_RELEASE_PUBLIC_KEY_PATH}")
					endif()
					if(NOT "${_lcc_signature_algorithm}" STREQUAL "rsa-pkcs1-sha256")
						list(APPEND _lcc_artifact_violations "release signature algorithm is unsupported: ${_lcc_signature_algorithm}")
					endif()
				endif()
			endif()
		endif()
		if(DEFINED LCC_RELEASE_PROPERTIES_PATH)
			_lcc_resolve_manifest_path(_lcc_properties_abs _lcc_properties_path_ok "${LCC_RELEASE_PROPERTIES_PATH}")
			if(NOT _lcc_properties_path_ok)
				list(APPEND _lcc_artifact_violations "release manifest properties path is unsafe: ${LCC_RELEASE_PROPERTIES_PATH}")
			elseif(NOT EXISTS "${_lcc_properties_abs}")
				list(APPEND _lcc_artifact_violations "release manifest properties path is missing: ${LCC_RELEASE_PROPERTIES_PATH}")
			elseif(DEFINED LCC_RELEASE_PROPERTIES_SHA256)
				file(SHA256 "${_lcc_properties_abs}" _lcc_properties_sha256)
				if(NOT _lcc_properties_sha256 STREQUAL "${LCC_RELEASE_PROPERTIES_SHA256}")
					list(APPEND _lcc_artifact_violations "release manifest properties SHA256 does not match ${LCC_RELEASE_PROPERTIES_PATH}")
				endif()
			endif()
			if(EXISTS "${_lcc_properties_abs}")
				_lcc_read_public_key_numeric_define(_lcc_properties_license_format_min "${_lcc_properties_abs}" LCC_SUPPORTED_LICENSE_FORMAT_MIN)
				_lcc_read_public_key_numeric_define(_lcc_properties_license_format_max "${_lcc_properties_abs}" LCC_SUPPORTED_LICENSE_FORMAT_MAX)
				if("${_lcc_properties_license_format_min}" STREQUAL "")
					list(APPEND _lcc_artifact_violations "release manifest license format minimum is missing from ${LCC_RELEASE_PROPERTIES_PATH}")
				elseif(NOT "${_lcc_properties_license_format_min}" MATCHES "^[0-9]+$")
					list(APPEND _lcc_artifact_violations "release manifest license format minimum is not numeric in ${LCC_RELEASE_PROPERTIES_PATH}: ${_lcc_properties_license_format_min}")
				elseif(DEFINED LCC_RELEASE_LICENSE_FORMAT_MIN AND
					   NOT "${_lcc_properties_license_format_min}" STREQUAL "${LCC_RELEASE_LICENSE_FORMAT_MIN}")
					list(APPEND _lcc_artifact_violations "release manifest license format minimum does not match ${LCC_RELEASE_PROPERTIES_PATH}")
				endif()
				if("${_lcc_properties_license_format_max}" STREQUAL "")
					list(APPEND _lcc_artifact_violations "release manifest license format maximum is missing from ${LCC_RELEASE_PROPERTIES_PATH}")
				elseif(NOT "${_lcc_properties_license_format_max}" MATCHES "^[0-9]+$")
					list(APPEND _lcc_artifact_violations "release manifest license format maximum is not numeric in ${LCC_RELEASE_PROPERTIES_PATH}: ${_lcc_properties_license_format_max}")
				elseif(DEFINED LCC_RELEASE_LICENSE_FORMAT_MAX AND
					   NOT "${_lcc_properties_license_format_max}" STREQUAL "${LCC_RELEASE_LICENSE_FORMAT_MAX}")
					list(APPEND _lcc_artifact_violations "release manifest license format maximum does not match ${LCC_RELEASE_PROPERTIES_PATH}")
				endif()
			endif()
		endif()
	endif()
endif()

if(_lcc_artifact_violations)
	string(REPLACE ";" "\n  " _lcc_artifact_report "${_lcc_artifact_violations}")
	message(FATAL_ERROR "Release artifact scan failed under ${LCC_ARTIFACT_SCAN_ROOT}:\n  ${_lcc_artifact_report}")
endif()
