include("${CMAKE_CURRENT_LIST_DIR}/ValidateLicenseccIdentity.cmake")

function(_lcc_require_manifest_value name)
	if(NOT DEFINED ${name} OR "${${name}}" STREQUAL "")
		message(FATAL_ERROR "${name} is required to write the release manifest")
	endif()
endfunction()

function(_lcc_manifest_append_set file_path name value)
	string(REPLACE "\\" "\\\\" _escaped "${value}")
	string(REPLACE "\"" "\\\"" _escaped "${_escaped}")
	file(APPEND "${file_path}" "set(${name} \"${_escaped}\")\n")
endfunction()

function(_lcc_read_public_key_numeric_define out_var public_key_header define_name)
	set(${out_var} "" PARENT_SCOPE)
	file(STRINGS "${public_key_header}" _lcc_public_key_numeric_lines
		REGEX "^[ \t]*#define[ \t]+${define_name}[ \t]+[^ \t]+[ \t]*$"
		LIMIT_COUNT 1)
	if(NOT _lcc_public_key_numeric_lines)
		return()
	endif()
	list(GET _lcc_public_key_numeric_lines 0 _lcc_public_key_numeric_line)
	string(REGEX REPLACE "^[ \t]*#define[ \t]+${define_name}[ \t]+([^ \t]+)[ \t]*$" "\\1"
		_lcc_public_key_numeric_value "${_lcc_public_key_numeric_line}")
	set(${out_var} "${_lcc_public_key_numeric_value}" PARENT_SCOPE)
endfunction()

function(_lcc_read_public_key_string_define out_var public_key_header define_name)
	set(${out_var} "" PARENT_SCOPE)
	file(STRINGS "${public_key_header}" _lcc_public_key_string_lines
		REGEX "^[ \t]*#define[ \t]+${define_name}[ \t]+\"[^\"]*\"[ \t]*$"
		LIMIT_COUNT 1)
	if(NOT _lcc_public_key_string_lines)
		return()
	endif()
	list(GET _lcc_public_key_string_lines 0 _lcc_public_key_string_line)
	string(REGEX REPLACE "^[ \t]*#define[ \t]+${define_name}[ \t]+\"([^\"]*)\"[ \t]*$" "\\1"
		_lcc_public_key_string_value "${_lcc_public_key_string_line}")
	set(${out_var} "${_lcc_public_key_string_value}" PARENT_SCOPE)
endfunction()

function(_lcc_read_public_key_der_len out_var public_key_header)
	_lcc_read_public_key_numeric_define(_lcc_public_key_len "${public_key_header}" PUBLIC_KEY_LEN)
	set(${out_var} "${_lcc_public_key_len}" PARENT_SCOPE)
endfunction()

_lcc_require_manifest_value(LCC_ARTIFACT_ROOT)
_lcc_require_manifest_value(LCC_ARTIFACT_PROJECT_NAME)
_lcc_require_manifest_value(LCC_ARTIFACT_PROJECT_MAGIC_NUM)
_lcc_require_manifest_value(LCC_ARTIFACT_PACKAGE_NAME)
_lcc_require_manifest_value(LCC_ARTIFACT_PACKAGE_VERSION)
_lcc_require_manifest_value(LCC_ARTIFACT_PACKAGE_PROFILE)
_lcc_require_manifest_value(LCC_ARTIFACT_LICENSE_FORMAT_MIN)
_lcc_require_manifest_value(LCC_ARTIFACT_LICENSE_FORMAT_MAX)

lcc_validate_project_name("${LCC_ARTIFACT_PROJECT_NAME}")
lcc_validate_project_magic_num("${LCC_ARTIFACT_PROJECT_MAGIC_NUM}")
lcc_validate_package_profile("${LCC_ARTIFACT_PACKAGE_PROFILE}")

if(NOT DEFINED LCC_ARTIFACT_BUILD_CONFIG)
	set(LCC_ARTIFACT_BUILD_CONFIG "")
endif()
if(NOT DEFINED LCC_ARTIFACT_PLATFORM)
	set(LCC_ARTIFACT_PLATFORM "")
endif()
if(NOT DEFINED LCC_ARTIFACT_SYSTEM_PROCESSOR)
	set(LCC_ARTIFACT_SYSTEM_PROCESSOR "")
endif()
if(NOT DEFINED LCC_ARTIFACT_GENERATOR)
	set(LCC_ARTIFACT_GENERATOR "")
endif()
if(NOT DEFINED LCC_ARTIFACT_COMPILER_ID)
	set(LCC_ARTIFACT_COMPILER_ID "")
endif()
if(NOT DEFINED LCC_ARTIFACT_COMPILER_VERSION)
	set(LCC_ARTIFACT_COMPILER_VERSION "")
endif()
if(NOT DEFINED LCC_ARTIFACT_COMPILER_ARCHITECTURE)
	set(LCC_ARTIFACT_COMPILER_ARCHITECTURE "")
endif()
if(NOT DEFINED LCC_ARTIFACT_RUNTIME_LINKAGE)
	set(LCC_ARTIFACT_RUNTIME_LINKAGE "")
endif()
if(NOT DEFINED LCC_ARTIFACT_ABI_TAG)
	set(LCC_ARTIFACT_ABI_TAG "")
endif()
if(NOT "${LCC_ARTIFACT_LICENSE_FORMAT_MIN}" MATCHES "^[0-9]+$")
	message(FATAL_ERROR "LCC_ARTIFACT_LICENSE_FORMAT_MIN must be numeric: ${LCC_ARTIFACT_LICENSE_FORMAT_MIN}")
endif()
if(NOT "${LCC_ARTIFACT_LICENSE_FORMAT_MAX}" MATCHES "^[0-9]+$")
	message(FATAL_ERROR "LCC_ARTIFACT_LICENSE_FORMAT_MAX must be numeric: ${LCC_ARTIFACT_LICENSE_FORMAT_MAX}")
endif()
if(LCC_ARTIFACT_LICENSE_FORMAT_MIN GREATER LCC_ARTIFACT_LICENSE_FORMAT_MAX)
	message(FATAL_ERROR "LCC_ARTIFACT_LICENSE_FORMAT_MIN must not exceed LCC_ARTIFACT_LICENSE_FORMAT_MAX")
endif()

get_filename_component(LCC_ARTIFACT_ROOT "${LCC_ARTIFACT_ROOT}" ABSOLUTE)
set(_lcc_public_key_rel "include/licensecc/${LCC_ARTIFACT_PROJECT_NAME}/public_key.h")
set(_lcc_properties_rel "include/licensecc/${LCC_ARTIFACT_PROJECT_NAME}/licensecc_properties.h")
set(_lcc_public_key "${LCC_ARTIFACT_ROOT}/${_lcc_public_key_rel}")
set(_lcc_properties "${LCC_ARTIFACT_ROOT}/${_lcc_properties_rel}")

if(NOT EXISTS "${_lcc_public_key}")
	message(FATAL_ERROR "Cannot write release manifest: public key is missing: ${_lcc_public_key}")
endif()
if(NOT EXISTS "${_lcc_properties}")
	message(FATAL_ERROR "Cannot write release manifest: generated properties are missing: ${_lcc_properties}")
endif()

file(SHA256 "${_lcc_public_key}" _lcc_public_key_sha256)
file(SHA256 "${_lcc_properties}" _lcc_properties_sha256)
_lcc_read_public_key_der_len(_lcc_public_key_der_len "${_lcc_public_key}")
if("${_lcc_public_key_der_len}" STREQUAL "")
	message(FATAL_ERROR "Cannot write release manifest: public key length is missing from ${_lcc_public_key}")
endif()
if(NOT "${_lcc_public_key_der_len}" MATCHES "^[0-9]+$")
	message(FATAL_ERROR "Cannot write release manifest: public key length is not numeric in ${_lcc_public_key}: ${_lcc_public_key_der_len}")
endif()
_lcc_read_public_key_string_define(_lcc_public_key_algorithm "${_lcc_public_key}" LCC_PUBLIC_KEY_ALGORITHM)
if("${_lcc_public_key_algorithm}" STREQUAL "")
	message(FATAL_ERROR "Cannot write release manifest: public key algorithm is missing from ${_lcc_public_key}")
endif()
if(NOT "${_lcc_public_key_algorithm}" STREQUAL "rsa")
	message(FATAL_ERROR "Cannot write release manifest: public key algorithm is unsupported in ${_lcc_public_key}: ${_lcc_public_key_algorithm}; expected rsa")
endif()
_lcc_read_public_key_numeric_define(_lcc_public_key_bits "${_lcc_public_key}" LCC_PUBLIC_KEY_BITS)
if("${_lcc_public_key_bits}" STREQUAL "")
	message(FATAL_ERROR "Cannot write release manifest: public key bit length is missing from ${_lcc_public_key}")
endif()
if(NOT "${_lcc_public_key_bits}" MATCHES "^[0-9]+$")
	message(FATAL_ERROR "Cannot write release manifest: public key bit length is not numeric in ${_lcc_public_key}: ${_lcc_public_key_bits}")
endif()
_lcc_read_public_key_string_define(_lcc_public_key_der_sha256 "${_lcc_public_key}" LCC_PUBLIC_KEY_SHA256)
if("${_lcc_public_key_der_sha256}" STREQUAL "")
	message(FATAL_ERROR "Cannot write release manifest: public key DER SHA256 is missing from ${_lcc_public_key}")
endif()
if(NOT "${_lcc_public_key_der_sha256}" MATCHES "^[0-9a-f]+$")
	message(FATAL_ERROR "Cannot write release manifest: public key DER SHA256 is not lowercase hex in ${_lcc_public_key}")
endif()
string(LENGTH "${_lcc_public_key_der_sha256}" _lcc_public_key_der_sha256_len)
if(NOT _lcc_public_key_der_sha256_len EQUAL 64)
	message(FATAL_ERROR "Cannot write release manifest: public key DER SHA256 has wrong length in ${_lcc_public_key}")
endif()
_lcc_read_public_key_string_define(_lcc_public_key_id "${_lcc_public_key}" LCC_PUBLIC_KEY_ID)
if("${_lcc_public_key_id}" STREQUAL "")
	message(FATAL_ERROR "Cannot write release manifest: public key ID is missing from ${_lcc_public_key}")
endif()
if(NOT "${_lcc_public_key_id}" STREQUAL "sha256:${_lcc_public_key_der_sha256}")
	message(FATAL_ERROR "Cannot write release manifest: public key ID does not match DER SHA256 in ${_lcc_public_key}")
endif()
_lcc_read_public_key_string_define(_lcc_signature_algorithm "${_lcc_public_key}" LCC_SIGNATURE_ALGORITHM)
if("${_lcc_signature_algorithm}" STREQUAL "")
	message(FATAL_ERROR "Cannot write release manifest: signature algorithm is missing from ${_lcc_public_key}")
endif()
if(NOT "${_lcc_signature_algorithm}" STREQUAL "rsa-pkcs1-sha256")
	message(FATAL_ERROR "Cannot write release manifest: signature algorithm is unsupported in ${_lcc_public_key}: ${_lcc_signature_algorithm}; expected rsa-pkcs1-sha256")
endif()
_lcc_read_public_key_numeric_define(_lcc_properties_license_format_min "${_lcc_properties}" LCC_SUPPORTED_LICENSE_FORMAT_MIN)
_lcc_read_public_key_numeric_define(_lcc_properties_license_format_max "${_lcc_properties}" LCC_SUPPORTED_LICENSE_FORMAT_MAX)
if("${_lcc_properties_license_format_min}" STREQUAL "")
	message(FATAL_ERROR "Cannot write release manifest: supported license format minimum is missing from ${_lcc_properties}")
endif()
if("${_lcc_properties_license_format_max}" STREQUAL "")
	message(FATAL_ERROR "Cannot write release manifest: supported license format maximum is missing from ${_lcc_properties}")
endif()
if(NOT "${_lcc_properties_license_format_min}" MATCHES "^[0-9]+$")
	message(FATAL_ERROR "Cannot write release manifest: supported license format minimum is not numeric in ${_lcc_properties}: ${_lcc_properties_license_format_min}")
endif()
if(NOT "${_lcc_properties_license_format_max}" MATCHES "^[0-9]+$")
	message(FATAL_ERROR "Cannot write release manifest: supported license format maximum is not numeric in ${_lcc_properties}: ${_lcc_properties_license_format_max}")
endif()
if(NOT "${_lcc_properties_license_format_min}" STREQUAL "${LCC_ARTIFACT_LICENSE_FORMAT_MIN}" OR
   NOT "${_lcc_properties_license_format_max}" STREQUAL "${LCC_ARTIFACT_LICENSE_FORMAT_MAX}")
	message(FATAL_ERROR "Cannot write release manifest: supported license format range in ${_lcc_properties} (${_lcc_properties_license_format_min}-${_lcc_properties_license_format_max}) does not match artifact metadata (${LCC_ARTIFACT_LICENSE_FORMAT_MIN}-${LCC_ARTIFACT_LICENSE_FORMAT_MAX})")
endif()

set(_lcc_manifest_dir "${LCC_ARTIFACT_ROOT}/share/licensecc/${LCC_ARTIFACT_PROJECT_NAME}")
set(_lcc_manifest "${_lcc_manifest_dir}/release-manifest.cmake")
file(MAKE_DIRECTORY "${_lcc_manifest_dir}")
file(WRITE "${_lcc_manifest}" "")

_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_MANIFEST_VERSION "1")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PACKAGE_NAME "${LCC_ARTIFACT_PACKAGE_NAME}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PACKAGE_VERSION "${LCC_ARTIFACT_PACKAGE_VERSION}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PACKAGE_PROFILE "${LCC_ARTIFACT_PACKAGE_PROFILE}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_LICENSE_FORMAT_MIN "${_lcc_properties_license_format_min}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_LICENSE_FORMAT_MAX "${_lcc_properties_license_format_max}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PROJECT_NAME "${LCC_ARTIFACT_PROJECT_NAME}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PROJECT_MAGIC_NUM "${LCC_ARTIFACT_PROJECT_MAGIC_NUM}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_BUILD_CONFIG "${LCC_ARTIFACT_BUILD_CONFIG}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PLATFORM "${LCC_ARTIFACT_PLATFORM}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_SYSTEM_PROCESSOR "${LCC_ARTIFACT_SYSTEM_PROCESSOR}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_GENERATOR "${LCC_ARTIFACT_GENERATOR}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_COMPILER_ID "${LCC_ARTIFACT_COMPILER_ID}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_COMPILER_VERSION "${LCC_ARTIFACT_COMPILER_VERSION}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_COMPILER_ARCHITECTURE "${LCC_ARTIFACT_COMPILER_ARCHITECTURE}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_RUNTIME_LINKAGE "${LCC_ARTIFACT_RUNTIME_LINKAGE}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_ABI_TAG "${LCC_ARTIFACT_ABI_TAG}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PUBLIC_KEY_PATH "${_lcc_public_key_rel}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PUBLIC_KEY_SHA256 "${_lcc_public_key_sha256}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PUBLIC_KEY_DER_SHA256 "${_lcc_public_key_der_sha256}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PUBLIC_KEY_ID "${_lcc_public_key_id}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PUBLIC_KEY_DER_LEN "${_lcc_public_key_der_len}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PUBLIC_KEY_ALGORITHM "${_lcc_public_key_algorithm}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PUBLIC_KEY_BITS "${_lcc_public_key_bits}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_SIGNATURE_ALGORITHM "${_lcc_signature_algorithm}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PROPERTIES_PATH "${_lcc_properties_rel}")
_lcc_manifest_append_set("${_lcc_manifest}" LCC_RELEASE_PROPERTIES_SHA256 "${_lcc_properties_sha256}")
