name: Linux_CI
on: [push, pull_request]
jobs:
   build-linux:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          build_type: ["Debug", "Release"]

      steps:
      -  uses: actions/checkout@v4
         with:
            submodules: recursive
      -  name: Install dependencies
         run: |
            sudo apt-get update
            sudo apt-get install -y cmake libssl-dev zlib1g-dev \
              libboost-dev libboost-test-dev libboost-filesystem-dev \
              libboost-iostreams-dev libboost-program-options-dev \
              libboost-system-dev libboost-thread-dev libboost-date-time-dev
      -  name: Compile
         run: |
            cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DLCC_PROJECT_NAME=test -DCMAKE_INSTALL_PREFIX=$PWD/install
            cmake --build build --target install -j$(nproc)
      -  name: Test
         working-directory: build
         run: ctest --output-on-failure
         env:
            CTEST_OUTPUT_ON_FAILURE: 1
            VIRTUAL_ENV: VM
      -  name: On failure print logs
         if: ${{ failure() }}
         run: cat /tmp/open-license.log || true
